const DATA_VERSION = "20260602-voci13";
const byId = (id) => document.getElementById(id);
const baseModules = [
  ["start","Start: hej und tack","Begrüßung, Höflichkeit",["Hallo!","Danke.","Entschuldigung.","Auf Wiedersehen."],["Hej!","Tack.","Ursäkta.","Hej då."]],
  ["intro","Selbstvorstellung","Name, Herkunft, Wohnort",["Ich heiße Jay.","Ich komme aus der Schweiz.","Ich wohne in Turbenthal.","Ich spreche ein bisschen Schwedisch."],["Jag heter Jay.","Jag kommer från Schweiz.","Jag bor i Turbenthal.","Jag talar lite svenska."]],
  ["questions","Fragen und Antworten","Ja/Nein und W-Fragen",["Wie heißt du?","Wo wohnst du?","Welche Sprachen sprichst du?","Kannst du Schwedisch sprechen?"],["Vad heter du?","Var bor du?","Vilka språk talar du?","Kan du tala svenska?"]],
  ["pronouns","Pronomen und är","jag, du, han, hon, vi",["Ich bin Jay.","Du bist nett.","Er ist müde.","Wir sind in der Schweiz."],["Jag är Jay.","Du är snäll.","Han är trött.","Vi är i Schweiz."]],
  ["numbers","Zahlen","0-100, Alter, Preis",["Ich bin 35 Jahre alt.","Es kostet 100 Kronen.","Ich habe zwei Kinder.","Meine Telefonnummer ist 123."],["Jag är 35 år.","Det kostar 100 kronor.","Jag har två barn.","Mitt telefonnummer är 123."]],
  ["alphabet","Buchstabieren","Name, E-Mail, Aussprache",["Wie schreibt man das?","Ich heiße Jay.","Meine E-Mail ist jay@example.com.","Kannst du wiederholen?"],["Hur stavas det?","Jag heter Jay.","Min e-post är jay@example.com.","Kan du upprepa?"]],
  ["languages","Sprachen und Lernen","talar, lär mig",["Ich spreche Deutsch und Englisch.","Ich spreche nicht viel Schwedisch.","Ich lerne Schwedisch.","Meine Schwester lernt Schwedisch."],["Jag talar tyska och engelska.","Jag talar inte mycket svenska.","Jag lär mig svenska.","Min syster lär sig svenska."]],
  ["family","Familie","har, ingen, inga",["Ich habe eine Familie.","Ich habe eine Schwester.","Ich habe keinen Bruder.","Ich habe keine Kinder."],["Jag har en familj.","Jag har en syster.","Jag har ingen bror.","Jag har inga barn."]],
  ["possessive","Besitz","min, mitt, mina, din",["Meine Mutter wohnt in der Schweiz.","Mein Kind spricht Deutsch.","Meine Kinder wohnen hier.","Deine Schwester lernt Schwedisch."],["Min mamma bor i Schweiz.","Mitt barn talar tyska.","Mina barn bor här.","Din syster lär sig svenska."]],
  ["work","Arbeit","arbetar med, arbetar i",["Ich arbeite mit Transport.","Ich arbeite mit Logistik.","Ich arbeite in Volketswil.","Ich arbeite nicht in Zürich."],["Jag arbetar med transport.","Jag arbetar med logistik.","Jag arbetar i Volketswil.","Jag arbetar inte i Zürich."]],
  ["articles","en/ett und Substantive","unbestimmt, bestimmt",["ein Auto.","das Auto.","ein Haus.","das Haus."],["En bil.","Bilen.","Ett hus.","Huset."]],
  ["plural","Plural einfach","ein, viele, keine",["Ich habe ein Kind.","Ich habe zwei Kinder.","Ich habe keine Kinder.","Ich habe viele Freunde."],["Jag har ett barn.","Jag har två barn.","Jag har inga barn.","Jag har många vänner."]],
  ["adjectives","Eigenschaften","gut, groß, klein, müde",["Das Auto ist groß.","Das Haus ist groß.","Ich bin müde.","Schwedisch ist gut."],["Bilen är stor.","Huset är stort.","Jag är trött.","Svenska är bra."]],
  ["day","Tagesablauf","äter, dricker, jobbar",["Ich esse Frühstück.","Ich trinke Kaffee.","Ich arbeite in Volketswil.","Ich lerne Schwedisch."],["Jag äter frukost.","Jag dricker kaffe.","Jag jobbar i Volketswil.","Jag läser svenska."]],
  ["time","Uhrzeit und Tage","klockan, idag, imorgon",["Wie spät ist es?","Es ist acht Uhr.","Heute arbeite ich.","Morgen lerne ich Schwedisch."],["Vad är klockan?","Klockan är åtta.","Idag jobbar jag.","Imorgon läser jag svenska."]],
  ["food","Essen und Trinken","Restaurant, Café, Einkauf",["Ich möchte Kaffee.","Ich esse Frühstück.","Was kostet das?","Ich möchte bezahlen."],["Jag vill ha kaffe.","Jag äter frukost.","Vad kostar det?","Jag vill betala."]],
  ["shopping","Einkaufen","Preis, Größe, Hilfe",["Ich suche eine Jacke.","Haben Sie das in Blau?","Es ist zu teuer.","Ich nehme das."],["Jag letar efter en jacka.","Har ni den i blått?","Det är för dyrt.","Jag tar den."]],
  ["directions","Weg und Orte","wo, nach links, Bahnhof",["Wo ist der Bahnhof?","Gehen Sie geradeaus.","Biegen Sie links ab.","Ich wohne in der Nähe."],["Var ligger stationen?","Gå rakt fram.","Sväng vänster.","Jag bor nära."]],
  ["travel","Reisen und Verkehr","Bus, Zug, Ticket",["Ich möchte ein Ticket kaufen.","Wann fährt der Zug?","Der Bus kommt um acht.","Ich reise nach Stockholm."],["Jag vill köpa en biljett.","När går tåget?","Bussen kommer klockan åtta.","Jag reser till Stockholm."]],
  ["home","Wohnen","Wohnung, Zimmer, Möbel",["Ich wohne in einer Wohnung.","Meine Wohnung ist klein.","Ich habe ein Zimmer.","Die Küche ist groß."],["Jag bor i en lägenhet.","Min lägenhet är liten.","Jag har ett rum.","Köket är stort."]],
  ["weather","Wetter","kalt, warm, regnet",["Wie ist das Wetter?","Es ist kalt heute.","Es regnet.","Im Sommer ist es warm."],["Hur är vädret?","Det är kallt idag.","Det regnar.","På sommaren är det varmt."]],
  ["health","Körper und Gesundheit","Arzt, Schmerzen, müde",["Ich habe Kopfschmerzen.","Ich bin krank.","Ich brauche einen Arzt.","Mir geht es nicht gut."],["Jag har huvudvärk.","Jag är sjuk.","Jag behöver en läkare.","Jag mår inte bra."]],
  ["inte","Verneinung mit inte","inte nach dem ersten Verb",["Ich spreche nicht Schwedisch.","Ich kann nicht viel Schwedisch sprechen.","Ich will nicht in Zürich wohnen.","Meine Schwester lernt nicht Schwedisch."],["Jag talar inte svenska.","Jag kan inte tala mycket svenska.","Jag vill inte bo i Zürich.","Min syster lär sig inte svenska."]],
  ["modal","kan/vill + Grundform","tala, bo, lära mig",["Ich kann ein bisschen Schwedisch sprechen.","Ich will Schwedisch lernen.","Ich will in Schweden wohnen.","Ich kann nicht viel Schwedisch sprechen."],["Jag kan tala lite svenska.","Jag vill lära mig svenska.","Jag vill bo i Sverige.","Jag kan inte tala mycket svenska."]],
  ["wordorder","Wortstellung","Verb auf Position 2",["Heute arbeite ich in Volketswil.","Morgen lerne ich Schwedisch.","Am Abend trinke ich Kaffee.","Jetzt wohne ich in der Schweiz."],["Idag jobbar jag i Volketswil.","Imorgon läser jag svenska.","På kvällen dricker jag kaffe.","Nu bor jag i Schweiz."]],
  ["prepositions","Präpositionen","i, på, från, till, med",["Ich wohne in der Schweiz.","Ich arbeite bei einem Unternehmen.","Ich komme aus Zürich.","Ich fahre nach Stockholm."],["Jag bor i Schweiz.","Jag arbetar på ett företag.","Jag kommer från Zürich.","Jag åker till Stockholm."]],
  ["past","Vergangenheit light","var, hade, gjorde",["Gestern war ich zu Hause.","Ich hatte Kaffee.","Was hast du gestern gemacht?","Ich arbeitete gestern."],["Igår var jag hemma.","Jag hade kaffe.","Vad gjorde du igår?","Jag jobbade igår."]],
  ["future","Zukunft light","ska, vill, imorgon",["Morgen werde ich arbeiten.","Ich werde Schwedisch lernen.","Ich möchte nach Schweden reisen.","Nächste Woche kaufe ich ein Ticket."],["Imorgon ska jag jobba.","Jag ska lära mig svenska.","Jag vill resa till Sverige.","Nästa vecka köper jag en biljett."]],
  ["imperative","Bitten und Aufforderungen","kan du, hjälp mig, öppna",["Kannst du mir helfen?","Wiederhole bitte.","Sprich langsam.","Schreib das bitte."],["Kan du hjälpa mig?","Upprepa gärna.","Tala långsamt.","Skriv det gärna."]],
  ["dialog","Mini-Dialog","kurzer Alltag",["Schreibe einen Mini-Dialog mit Hej.","Frage: Wie geht es dir?","Antworte: Mir geht es gut, danke.","Frage zurück: Und dir?"],["Hej!","Hur mår du?","Jag mår bra, tack.","Och du?"]],
  ["a1review","A1-Abschlussrunde","frei kombinieren",["Schreibe 4-6 Sätze über dich.","Nutze mindestens einmal inte.","Nutze mindestens einmal kan oder vill.","Nutze ein Thema: Arbeit, Familie, Wohnen, Essen oder Reise."],["Jag heter Jay.","Jag bor i Turbenthal.","Jag kan tala lite svenska.","Jag arbetar med transport."]]
];
const nounPacks = [
  [["en tavla","Wandtafel"],["ett bord","Tisch"],["en stol","Stuhl"],["en lampa","Lampe"],["en dörr","Tür"],["ett fönster","Fenster"],["en säng","Bett"],["en bok","Buch"],["en penna","Stift"],["ett papper","Papier"]],
  [["ett kök","Küche"],["ett rum","Zimmer"],["en soffa","Sofa"],["en hylla","Regal"],["en dator","Computer"],["en telefon","Telefon"],["en nyckel","Schlüssel"],["en väska","Tasche"],["en jacka","Jacke"],["en sko","Schuh"]],
  [["en mamma","Mutter"],["en pappa","Vater"],["en bror","Bruder"],["en syster","Schwester"],["ett barn","Kind"],["en familj","Familie"],["en vän","Freund"],["en kvinna","Frau"],["en man","Mann"],["ett namn","Name"]],
  [["en tallrik","Teller"],["ett glas","Glas"],["en kopp","Tasse"],["en sked","Löffel"],["en gaffel","Gabel"],["en kniv","Messer"],["bröd","Brot"],["mjölk","Milch"],["vatten","Wasser"],["kaffe","Kaffee"]],
  [["en buss","Bus"],["ett tåg","Zug"],["en bil","Auto"],["en cykel","Fahrrad"],["en gata","Straße"],["en station","Bahnhof"],["en biljett","Ticket"],["en karta","Karte"],["en stad","Stadt"],["ett hus","Haus"]]
];
function nounModule(pack,index){return {id:`nouns-${index+1}`,title:`Nomen-Voci ${index+1}`,tag:"A1 Nomen, Dinge und Alltag",tasks:pack.slice(0,6).map(([,de])=>`Schreibe: ${de}.`),expected:pack.slice(0,6).map(([sv])=>`${sv}.`),nounVocab:pack}}
function formatTask(task){return /^(Schreibe|Nutze|Frage|Antworte|Bilde|Beantworte|Ergänze|Prüfung):?/i.test(task)?task:`Schreibe: ${task}`}
const checkpointSets = [
  {title:"A1-Checkpoint 1",tag:"Prüfung: Begrüßung, Person, Fragen",pairs:[["Hallo!","Hej!"],["Ich heiße Jay.","Jag heter Jay."],["Wo wohnst du?","Var bor du?"],["Ich wohne in der Schweiz.","Jag bor i Schweiz."],["Ich spreche ein bisschen Schwedisch.","Jag talar lite svenska."],["Kannst du wiederholen?","Kan du upprepa?"]]},
  {title:"A1-Checkpoint 2",tag:"Prüfung: Familie, Besitz, Alltag",pairs:[["Ich habe eine Schwester.","Jag har en syster."],["Meine Mutter wohnt hier.","Min mamma bor här."],["Ich habe keinen Bruder.","Jag har ingen bror."],["Mein Kind spricht Deutsch.","Mitt barn talar tyska."],["Das Haus ist groß.","Huset är stort."],["Ich bin müde.","Jag är trött."]]},
  {title:"A1-Checkpoint 3",tag:"Prüfung: Zeit, Essen, Einkauf",pairs:[["Heute arbeite ich.","Idag jobbar jag."],["Es ist acht Uhr.","Klockan är åtta."],["Ich möchte Kaffee.","Jag vill ha kaffe."],["Was kostet das?","Vad kostar det?"],["Ich suche eine Jacke.","Jag letar efter en jacka."],["Ich nehme das.","Jag tar den."]]},
  {title:"A1-Checkpoint 4",tag:"Prüfung: Weg, Reise, Wohnen",pairs:[["Wo ist der Bahnhof?","Var ligger stationen?"],["Gehen Sie geradeaus.","Gå rakt fram."],["Ich möchte ein Ticket kaufen.","Jag vill köpa en biljett."],["Der Bus kommt um acht.","Bussen kommer klockan åtta."],["Ich wohne in einer Wohnung.","Jag bor i en lägenhet."],["Die Küche ist groß.","Köket är stort."]]},
  {title:"A1-Checkpoint 5",tag:"Prüfung: Wetter, Gesundheit, Grammatik",pairs:[["Es ist kalt heute.","Det är kallt idag."],["Ich habe Kopfschmerzen.","Jag har huvudvärk."],["Ich spreche nicht Schwedisch.","Jag talar inte svenska."],["Ich kann ein bisschen Schwedisch sprechen.","Jag kan tala lite svenska."],["Morgen lerne ich Schwedisch.","Imorgon läser jag svenska."],["Ich komme aus Zürich.","Jag kommer från Zürich."]]}
];
function checkpointModule(set,index){return {id:`checkpoint-${index+1}`,title:set.title,tag:set.tag,tasks:set.pairs.map(([de])=>`Prüfung: ${de}`),expected:set.pairs.map(([,sv])=>sv),checkpoint:true}}
const modules = baseModules.reduce((list,[id,title,tag,tasks,expected],index)=>{list.push({id,title,tag,tasks:tasks.map(formatTask),expected});if((index+1)%2===0)list.push(nounModule(nounPacks[Math.floor(index/2)%nounPacks.length],Math.floor(index/2)));if((index+1)%6===0&&checkpointSets[Math.floor(index/6)])list.push(checkpointModule(checkpointSets[Math.floor(index/6)],Math.floor(index/6)));return list},[]);
const extraWords = {
  start:[["Hej","Hallo"],["Tack","Danke"],["Ursäkta","Entschuldigung"],["Hej då","Auf Wiedersehen"],["God morgon","Guten Morgen"],["God kväll","Guten Abend"],["Vi ses","Wir sehen uns"],["Ja","Ja"],["Nej","Nein"],["Varsågod","Bitte / gern"],["Förlåt","Verzeihung"],["Okej","Okay"]],
  intro:[["jag","ich"],["du","du"],["han","er"],["hon","sie"],["det","es"],["vi","wir"],["ni","ihr / Sie"],["de","sie"],["Sverige","Schweden"],["Schweiz","Schweiz"],["bor","wohne"],["kommer från","komme aus"],["lite","ein bisschen"],["namn","Name"]],
  questions:[["Vad","Was"],["Var","Wo"],["Vem","Wer"],["Hur","Wie"],["Vilka","Welche"],["Kan","Kann"],["du","du"],["ni","ihr / Sie"],["fråga","Frage"],["svar","Antwort"],["språk","Sprache"],["svenska","Schwedisch"]],
  pronouns:[["jag","ich"],["du","du"],["han","er"],["hon","sie"],["det","es"],["vi","wir"],["ni","ihr"],["de","sie"],["är","bin / bist / ist"],["snäll","nett"],["trött","müde"],["här","hier"]],
  alphabet:[["bokstav","Buchstabe"],["stavas","wird buchstabiert"],["upprepa","wiederholen"],["långsamt","langsam"],["snälla","bitte"],["e-post","E-Mail"],["punkt","Punkt"],["snabel-a","At-Zeichen"],["förnamn","Vorname"],["efternamn","Nachname"]],
  languages:[["tyska","Deutsch"],["engelska","Englisch"],["svenska","Schwedisch"],["språk","Sprache"],["lär mig","lerne"],["talar","spreche"],["förstår","verstehe"],["skriver","schreibe"],["läser","lese"],["mycket","viel"],["lite","wenig / ein bisschen"]],
  family:[["en bror","Bruder"],["en syster","Schwester"],["en mamma","Mutter"],["en pappa","Vater"],["ett barn","Kind"],["en familj","Familie"],["en vän","Freund"],["min","mein / meine"],["din","dein / deine"],["ingen","kein"]],
  possessive:[["min","mein / meine"],["mitt","mein / meine"],["mina","meine"],["din","dein / deine"],["ditt","dein / deine"],["dina","deine"],["här","hier"],["hemma","zu Hause"],["ett barn","Kind"],["en mamma","Mutter"],["en pappa","Vater"]],
  work:[["arbetar","arbeite"],["jobbar","arbeite"],["ett arbete","Arbeit"],["ett företag","Unternehmen"],["transport","Transport"],["logistik","Logistik"],["kontor","Büro"],["kollega","Kollege"],["chef","Chef"],["idag","heute"]],
  articles:[["en bil","ein Auto"],["bilen","das Auto"],["ett hus","ein Haus"],["huset","das Haus"],["en bok","ein Buch"],["boken","das Buch"],["ett bord","ein Tisch"],["bordet","der Tisch"],["en dörr","eine Tür"],["dörren","die Tür"]],
  plural:[["ett barn","ein Kind"],["två barn","zwei Kinder"],["en vän","ein Freund"],["många vänner","viele Freunde"],["en bok","ein Buch"],["tre böcker","drei Bücher"],["inga barn","keine Kinder"],["många","viele"],["få","wenige"],["några","einige"]],
  adjectives:[["stor","groß"],["stort","groß"],["liten","klein"],["litet","klein"],["bra","gut"],["dålig","schlecht"],["trött","müde"],["snäll","nett"],["kall","kalt"],["varm","warm"]],
  day:[["äter","esse"],["dricker","trinke"],["jobbar","arbeite"],["läser","lerne / lese"],["sover","schlafe"],["går","gehe"],["kommer","komme"],["morgon","Morgen"],["kväll","Abend"],["frukost","Frühstück"]],
  time:[["klockan","Uhr"],["idag","heute"],["imorgon","morgen"],["igår","gestern"],["måndag","Montag"],["tisdag","Dienstag"],["onsdag","Mittwoch"],["vecka","Woche"],["år","Jahr"],["tid","Zeit"]],
  numbers:[["noll","null"],["ett","eins"],["två","zwei"],["tre","drei"],["fyra","vier"],["fem","fünf"],["sex","sechs"],["sju","sieben"],["åtta","acht"],["nio","neun"],["tio","zehn"],["hundra","hundert"]],
  food:[["vatten","Wasser"],["bröd","Brot"],["frukost","Frühstück"],["mjölk","Milch"],["kaffe","Kaffee"],["te","Tee"],["mat","Essen"],["en kopp","Tasse"],["ett glas","Glas"],["betala","bezahlen"]],
  shopping:[["letar efter","suche"],["en jacka","Jacke"],["blått","blau"],["dyrt","teuer"],["billigt","billig"],["storlek","Größe"],["hjälp","Hilfe"],["pengar","Geld"],["kvitto","Quittung"],["tar","nehme"]],
  directions:[["stationen","Bahnhof"],["rakt fram","geradeaus"],["vänster","links"],["höger","rechts"],["nära","nahe"],["långt","weit"],["gata","Straße"],["här","hier"],["där","dort"],["ligger","liegt"]],
  travel:[["buss","Bus"],["tåg","Zug"],["biljett","Ticket"],["stationen","Bahnhof"],["gata","Straße"],["stad","Stadt"],["karta","Karte"],["höger","rechts"],["vänster","links"],["nära","nahe"]],
  home:[["en lägenhet","Wohnung"],["ett rum","Zimmer"],["ett kök","Küche"],["ett badrum","Badezimmer"],["en säng","Bett"],["ett bord","Tisch"],["en stol","Stuhl"],["en lampa","Lampe"],["liten","klein"],["stor","groß"]],
  weather:[["väder","Wetter"],["kallt","kalt"],["varmt","warm"],["regnar","regnet"],["snöar","schneit"],["sol","Sonne"],["moln","Wolken"],["sommar","Sommer"],["vinter","Winter"],["idag","heute"]],
  health:[["huvudvärk","Kopfschmerzen"],["sjuk","krank"],["läkare","Arzt"],["mår","geht es"],["bra","gut"],["dåligt","schlecht"],["trött","müde"],["ont","Schmerzen"],["hjälp","Hilfe"],["behöver","brauche"]],
  inte:[["inte","nicht"],["talar inte","spreche nicht"],["kan inte","kann nicht"],["vill inte","will nicht"],["lär sig inte","lernt nicht"],["mycket","viel"],["svenska","Schwedisch"],["bo","wohnen"],["Zürich","Zürich"],["syster","Schwester"]],
  modal:[["kan","kann"],["vill","will / möchte"],["måste","muss"],["tala","sprechen"],["bo","wohnen"],["lära mig","lernen"],["resa","reisen"],["köpa","kaufen"],["hjälpa","helfen"],["lite","ein bisschen"]],
  wordorder:[["idag","heute"],["imorgon","morgen"],["på kvällen","am Abend"],["nu","jetzt"],["jobbar","arbeite"],["läser","lerne / lese"],["dricker","trinke"],["bor","wohne"],["verb","Verb"],["ordföljd","Wortstellung"]],
  prepositions:[["i","in"],["på","auf / bei"],["från","aus / von"],["till","nach / zu"],["med","mit"],["utan","ohne"],["hemma","zu Hause"],["företag","Unternehmen"],["Stockholm","Stockholm"],["Schweiz","Schweiz"]],
  past:[["igår","gestern"],["var","war"],["hade","hatte"],["gjorde","machte"],["jobbade","arbeitete"],["hemma","zu Hause"],["kaffe","Kaffee"],["frågade","fragte"],["köpte","kaufte"],["läste","las / lernte"]],
  future:[["imorgon","morgen"],["ska","werde"],["nästa vecka","nächste Woche"],["resa","reisen"],["köpa","kaufen"],["biljett","Ticket"],["lära mig","lernen"],["jobba","arbeiten"],["Sverige","Schweden"],["vill","möchte"]],
  imperative:[["hjälp mig","hilf mir"],["upprepa","wiederhole"],["tala långsamt","sprich langsam"],["skriv","schreib"],["öppna","öffne"],["stäng","schließe"],["lyssna","hör zu"],["läs","lies"],["kom","komm"],["gärna","gern / bitte"]],
  dialog:[["Hej","Hallo"],["Hur mår du?","Wie geht es dir?"],["Jag mår bra","Mir geht es gut"],["Och du?","Und dir?"],["Tack","Danke"],["Vi ses","Wir sehen uns"],["förlåt","Entschuldigung"],["ingen fara","kein Problem"],["ha det bra","mach's gut"],["hej då","auf Wiedersehen"]],
  a1review:[["presentera dig","stell dich vor"],["jag heter","ich heiße"],["jag bor","ich wohne"],["jag kommer från","ich komme aus"],["jag arbetar","ich arbeite"],["min familj","meine Familie"],["inte","nicht"],["kan","kann"],["vill","möchte"],["idag","heute"]]
};
const commonVocab = [["jag","ich"],["du","du"],["han","er"],["hon","sie"],["det","es"],["vi","wir"],["ni","ihr / Sie"],["de","sie"],["en bror","Bruder"],["en syster","Schwester"],["en mamma","Mutter"],["en pappa","Vater"],["ett barn","Kind"],["en vän","Freund"],["ett bord","Tisch"],["en säng","Bett"],["en lampa","Lampe"],["en dörr","Tür"],["ett fönster","Fenster"],["en bok","Buch"]];
const hints = ["Klingt nah am deutschen Satz - erst laut lesen, dann klicken.","Merke dir den Anfangsbuchstaben und sprich das Wort langsam.","Das Wort kommt gleich in der Aufgabe wieder vor.","Mini-Trick: baue daraus im Kopf einen kurzen Alltagssatz."];
const filler = [["och","und"],["inte","nicht"],["jag","ich"],["du","du"],["är","bin / bist / ist / sind"],["har","habe / hat"],["vill","will / möchte"],["kan","kann"],["idag","heute"],["imorgon","morgen"]];
const roastMessages = ["Hier hast du verkackt. Aber immerhin auf Schwedisch fast elegant.","Das war sprachlich ein Unfall mit Warnweste. Neuer Versuch.","Autsch. Dein Satz braucht weniger Drama und mehr Grammatik.","Knapp daneben ist auch vorbei. Wir schleifen das jetzt rein."];
const winMessages = ["Sauber. Das klingt langsam nach echtem Schwedisch.","Sehr gut. Gehirn hat heute Dienst.","Passt. Weiter, bevor du dich zu sehr feierst.","Stark. Das Thema ist nicht mehr dein Gegner."];
const defaultState = { activeModule: "start", today: 0, totalErrors: 0, errors: {}, modules: {} };
let state = loadState();
let lastCheckedPassed = null;
let lastCheckedMode = null;
let voices = [];
function loadState(){try{return {...structuredClone(defaultState),...(JSON.parse(localStorage.getItem("svenska-a1-state"))||{})}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem("svenska-a1-state",JSON.stringify(state));localStorage.setItem("svenska-a1-build",DATA_VERSION)}
function resetLegacy(){if(localStorage.getItem("svenska-a1-build")!==DATA_VERSION){localStorage.removeItem("svenska-a1-state");localStorage.setItem("svenska-a1-build",DATA_VERSION);state=structuredClone(defaultState);saveState()}}
function getModuleState(module){state.modules[module.id]={vocabStreak:0,correctStreak:0,status:"unsicher",variant:0,vocabVariant:0,vocabSeed:Date.now(),exerciseSeed:Date.now()+17,attempts:0,...(state.modules[module.id]||{})};return state.modules[module.id]}
function moduleIndex(id){return modules.findIndex((m)=>m.id===id)}
function isUnlocked(index){return index===0||modules.slice(0,index).every((m)=>getModuleState(m).status==="verstanden")}
function activeModule(){let index=moduleIndex(state.activeModule);if(index<0||!isUnlocked(index)){index=modules.findIndex((_,i)=>isUnlocked(i));state.activeModule=modules[Math.max(0,index)].id}return modules.find((m)=>m.id===state.activeModule)||modules[0]}
function normalize(text){return text.toLowerCase().replace(/[.,!?]/g,"").replace(/\s+/g," ").trim()}
function strip(text){return text.replace(/[.,!?]/g,"").trim()}
function taskGerman(task){return strip(task.replace(/^Schreibe:\s*/,"").replace(/^Zusatz:\s*Schreibe\s*/,"").replace(/^Prüfung:\s*/,"").replace(/^Frage:\s*/,"").replace(/^Antworte:\s*/,"").replace(/^"/,"").replace(/"$/,""))}
function nextSeed(){return Math.floor(Date.now()+Math.random()*1000000)}
function seededRandom(seed){let value=seed%2147483647;if(value<=0)value+=2147483646;return()=>{value=value*16807%2147483647;return(value-1)/2147483646}}
function shuffled(items,seed){const random=seededRandom(seed);const list=[...items];for(let i=list.length-1;i>0;i-=1){const j=Math.floor(random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function getVocab(module){const phraseVocab=module.expected.map((sentence,index)=>[strip(sentence),taskGerman(module.tasks[index]||guessGerman(strip(sentence)))]);const fromExpected=module.expected.flatMap((sentence)=>strip(sentence).split(" ")).filter((w)=>w.length>1).map((sv)=>[sv,guessGerman(sv)]).filter(([,de])=>de);const nounVocab=module.nounVocab||[];const merged=[...nounVocab,...(extraWords[module.id]||[]),...phraseVocab,...fromExpected,...commonVocab,...filler];const seen=new Set();return merged.filter(([sv,de])=>{const key=sv.toLowerCase();if(!de||seen.has(key))return false;seen.add(key);return true}).slice(0,28).map(([sv,de],i)=>({sv,de,hint:hints[i%hints.length]}))}
function guessGerman(sv){const map={Hej:"Hallo","Hej då":"Auf Wiedersehen",Tack:"Danke","Ursäkta":"Entschuldigung","God morgon":"Guten Morgen","God kväll":"Guten Abend","Vi ses":"Wir sehen uns",Ja:"Ja",Nej:"Nein","Varsågod":"Bitte / gern",Förlåt:"Verzeihung",Jag:"Ich",jag:"ich",Du:"Du",du:"du",Han:"Er",han:"er",Hon:"Sie",hon:"sie",det:"es",Vi:"Wir",vi:"wir",De:"Sie",de:"sie",Ni:"Ihr / Sie",ni:"ihr / Sie",heter:"heiße",kommer:"komme",från:"aus",bor:"wohne",talar:"spreche",svenska:"Schwedisch",tyska:"Deutsch",engelska:"Englisch",är:"bin / bist / ist / sind",snäll:"nett",trött:"müde",Schweiz:"Schweiz",Sverige:"Schweden",har:"habe / hat",inte:"nicht",vill:"will / möchte",kan:"kann",lära:"lernen",läser:"lerne / lese",mig:"mich / mir",sig:"sich",lite:"ein bisschen",mycket:"viel",kaffe:"Kaffee",barn:"Kind / Kinder",familj:"Familie",syster:"Schwester",bror:"Bruder",mamma:"Mutter",pappa:"Vater",vän:"Freund",bil:"Auto",Bilen:"das Auto",hus:"Haus",Huset:"das Haus",frukost:"Frühstück",vatten:"Wasser",bröd:"Brot",mjölk:"Milch",te:"Tee",mat:"Essen",biljett:"Ticket",stationen:"Bahnhof",gata:"Straße",stad:"Stadt",karta:"Karte",höger:"rechts",vänster:"links",nära:"nahe",idag:"heute",imorgon:"morgen",åtta:"acht",klockan:"Uhr",kostar:"kostet",kronor:"Kronen",tavla:"Wandtafel",bord:"Tisch",stol:"Stuhl",lampa:"Lampe",dörr:"Tür",fönster:"Fenster",säng:"Bett",bok:"Buch",penna:"Stift",papper:"Papier",kök:"Küche",rum:"Zimmer",soffa:"Sofa",hylla:"Regal",dator:"Computer",telefon:"Telefon",nyckel:"Schlüssel",väska:"Tasche",jacka:"Jacke",sko:"Schuh",tallrik:"Teller",glas:"Glas",kopp:"Tasse",sked:"Löffel",gaffel:"Gabel",kniv:"Messer",cykel:"Fahrrad"};return map[sv]||""}
function getVocabRound(module){const s=getModuleState(module);return shuffled(getVocab(module),s.vocabSeed+s.vocabVariant*97).slice(0,10)}
function unique(list){return [...new Set(list.filter(Boolean))]}
function getChoices(correct,module,index=0){const s=getModuleState(module);const all=unique([...getVocab(module),...filler.map(([sv,de])=>({sv,de}))].map((x)=>x.de).filter((de)=>de!==correct.de));return shuffled([correct.de,...shuffled(all,s.vocabSeed+index*31).slice(0,3)],s.vocabSeed+index*53)}
function exercise(module){const s=getModuleState(module);const basePairs=module.tasks.map((task,index)=>({task,expected:module.expected[index]}));const targetSize=module.checkpoint?10:9;const extras=shuffled(getVocab(module).filter((item)=>!module.expected.some((sentence)=>normalize(sentence).includes(normalize(item.sv)))),s.exerciseSeed+s.variant*131).slice(0,Math.max(0,targetSize-basePairs.length)).map((item)=>({task:`Zusatz: Schreibe "${item.de}".`,expected:item.sv}));const round=shuffled([...basePairs,...extras],s.exerciseSeed+s.variant*173);return {tasks:round.map((item)=>item.task),expected:round.map((item)=>item.expected)}}
function render(){const module=activeModule();const s=getModuleState(module);const vocab=s.vocabStreak<1;byId("moduleTag").textContent=module.tag;byId("moduleTitle").textContent=module.title;byId("topicStatus").textContent=vocab?`Voci ${s.vocabStreak}/1`:s.status;byId("difficulty").textContent=vocab?"Voci":"A1";byId("todayCount").textContent=state.today;byId("masteredCount").textContent=Object.values(state.modules).filter((m)=>m.status==="verstanden").length;byId("errorCount").textContent=state.totalErrors;renderModules();if(vocab){byId("taskTitle").textContent=`Voci vor "${module.title}"`;byId("taskList").innerHTML="<li>Beantworte 10 Wörter fehlerfrei.</li><li>Erst danach wird die Satzübung freigeschaltet.</li>";byId("answerForm").classList.add("hidden");byId("vocabForm").classList.remove("hidden");renderVocab(module)}else{const ex=exercise(module);byId("taskTitle").textContent=module.checkpoint?"A1-Checkpoint: gemischte Prüfung.":"Übung: ein längerer Durchgang.";byId("taskList").innerHTML=ex.tasks.map((t)=>`<li>${t}</li>`).join("");byId("vocabForm").classList.add("hidden");byId("answerForm").classList.remove("hidden")}renderFlowButton()}
function renderModules(){byId("moduleList").innerHTML=modules.map((m,i)=>{const s=getModuleState(m);const locked=!isUnlocked(i);return `<button class="module-button${m.id===state.activeModule?" active":""}${s.status==="verstanden"?" mastered":""}${locked?" locked":""}" data-module="${m.id}" type="button" ${locked?"disabled":""}>${m.title}<span>${locked?"Gesperrt · ":""}Voci ${s.vocabStreak}/1 · Übung ${Math.min(s.correctStreak,1)}/1 · ${s.status}</span></button>`}).join("")}
function renderVocab(module){const items=getVocabRound(module);byId("vocabForm").innerHTML=items.map((item,i)=>`<div class="vocab-card"><div class="vocab-word"><strong>${item.sv}</strong><span>Wort ${i+1}</span></div><div class="choice-grid">${getChoices(item,module,i).map((choice)=>`<label class="choice-option"><input type="radio" name="vocab-${i}" value="${choice}"><span>${choice}</span></label>`).join("")}</div></div>`).join("")+"<div class='actions'><button type='submit'>Voci prüfen</button></div>"}
function renderFlowButton(){const btn=byId("nextBtn");if(lastCheckedPassed===null){btn.classList.add("hidden");btn.hidden=true;return}btn.classList.remove("hidden");btn.hidden=false;btn.textContent=lastCheckedPassed?"WEITER":"NEUER VERSUCH"}
function renderFeedbackAction(passed){return `<div class="feedback-actions"><button class="feedback-flow-button ${passed?"success":"retry"}" data-feedback-flow="true" type="button">${passed?"WEITER":"NEUER VERSUCH"}</button></div>`}
function audioRows(lines){return `<div class="audio-list">${lines.map((line)=>`<div class="audio-row"><span>${line}</span><div class="speak-actions"><button class="speak-button" data-speak="${encodeURIComponent(line)}" type="button">▶</button><button class="speak-button slow" data-speak="${encodeURIComponent(line)}" data-speed="slow" type="button">½</button></div></div>`).join("")}</div>`}
function drillBlock(title,lines){const clean=[...new Set(lines.filter(Boolean))].slice(0,6);if(!clean.length)return "";return `<div class="feedback-item warn"><strong>${title}</strong><ol>${clean.map((line)=>`<li><em>${line}</em><br>Schreibe diesen Ausdruck 3x laut und sauber ab. Danach erst neu versuchen.${audioRows([line])}</li>`).join("")}</ol></div>`}
function restartNotice(){return `<div class="feedback-item bad"><strong>Runde nicht bestanden.</strong>Der Bereich startet danach neu mit frischen Fragen. Kein halbes Durchmogeln, heute wird sauber gelernt.</div>`}
function checkVocab(module){const items=getVocabRound(module);const mistakes=[];items.forEach((item,i)=>{const selected=byId("vocabForm").querySelector(`input[name="vocab-${i}"]:checked`);if(!selected||selected.value!==item.de)mistakes.push({...item,selected:selected?.value||"keine Antwort"})});return {passed:mistakes.length===0,mistakes,items}}
function textSentences(text){return text.split(/\n|[.!?]+/).map((line)=>line.trim()).filter(Boolean)}
function hasExpected(input,expected){const exp=normalize(expected);if(!exp)return true;if(exp.includes(" "))return input.includes(exp);return input.split(" ").includes(exp)}
function reviewCriteria(text){const input=normalize(text);const lines=textSentences(text);return [
  {label:"mindestens 5 kurze Sätze",ok:lines.length>=5},
  {label:"Name oder Wohnort genannt",ok:/\b(heter|bor|kommer)\b/.test(input)},
  {label:"mindestens eine Verneinung mit inte",ok:input.split(" ").includes("inte")},
  {label:"mindestens einmal kan oder vill",ok:input.split(" ").some((w)=>w==="kan"||w==="vill")},
  {label:"ein A1-Thema wie Familie, Arbeit, Wohnen, Essen oder Reise",ok:/\b(familj|mamma|pappa|syster|bror|arbete|jobbar|arbetar|lägenhet|rum|kaffe|frukost|resa|biljett)\b/.test(input)}
]}
function checkAnswer(text,ex,module){const input=normalize(text);if(module.id==="a1review"){const criteria=reviewCriteria(text);const passed=criteria.every((item)=>item.ok);const missing=criteria.filter((item)=>!item.ok).map((item)=>item.label);return {passed,hits:criteria.filter((item)=>item.ok).map((item)=>item.label),missing,criteria}}const hits=ex.expected.filter((x)=>hasExpected(input,x));const missing=ex.expected.filter((x)=>!hasExpected(input,x));const passed=missing.length===0;return {passed,hits,missing,criteria:[]}}
function applyVocab(result,module){const s=getModuleState(module);state.today+=1;s.attempts+=1;if(result.passed){s.vocabStreak=1;if(s.status==="unsicher")s.status="Voci bestanden";s.exerciseSeed=nextSeed()}else{s.vocabStreak=0;s.vocabVariant+=1;s.vocabSeed=nextSeed();state.totalErrors+=Math.max(1,result.mistakes.length);state.errors.Voci=(state.errors.Voci||0)+result.mistakes.length}saveState()}
function applyAnswer(result,module){const s=getModuleState(module);state.today+=1;s.attempts+=1;if(result.passed){s.correctStreak=1;s.status="verstanden"}else{s.exerciseSeed=nextSeed();state.totalErrors+=1;state.errors.Satzbau=(state.errors.Satzbau||0)+1;s.status="unsicher"}saveState();return result.passed&&s.status==="verstanden"}
function showVocabFeedback(result){const fb=byId("feedback");if(result.passed){fb.innerHTML=`<h3>Voci-Korrektur</h3><div class="feedback-item ok"><strong>Voci sitzt.</strong>Alle 10 Wörter korrekt. Die Satzübung ist frei.</div><div class="feedback-item ok"><strong>Audio freigeschaltet</strong>${audioRows(result.items.map((x)=>x.sv))}</div>${renderFeedbackAction(true)}`}else{fb.innerHTML=`<h3>Voci-Korrektur</h3>${restartNotice()}<div class="feedback-item warn"><strong>Voci verkackt.</strong>Hier sind die genauen Treffer ins Knie. Erst drillen, dann neu starten.</div>${result.mistakes.map((x)=>`<div class="feedback-item bad"><strong>${x.sv}</strong>Deine Wahl: ${x.selected}<br>Korrekt: <em>${x.de}</em></div>`).join("")}${drillBlock("Kurz-Drill vor dem Neustart",result.mistakes.flatMap((x)=>[`${x.sv} = ${x.de}`,x.sv]))}${renderFeedbackAction(false)}`}fb.classList.remove("hidden")}
function showAnswerFeedback(result,module,ex){const s=getModuleState(module);const fb=byId("feedback");const msg=result.passed?winMessages[Math.floor(Math.random()*winMessages.length)]:roastMessages[Math.floor(Math.random()*roastMessages.length)];let html=`<h3>Korrektur</h3><div class="feedback-item ${result.passed?"ok":"warn"}"><strong>${msg}</strong>${result.passed?"Übung bestanden: 1/1.":"Diese Runde zählt als nicht bestanden."}</div>`;if(result.criteria?.length)html+=`<div class="feedback-item ${result.passed?"ok":"warn"}"><strong>A1-Kriterien</strong>${result.criteria.map((item)=>`<br>${item.ok?"✓":"✗"} ${item.label}`).join("")}</div>`;if(!result.passed)html+=restartNotice();if(result.missing.length)html+=`<div class="feedback-item bad"><strong>Fehlt oder zu anders formuliert</strong>${result.missing.map((x)=>`<br><em>${x}</em>`).join("")}</div>${drillBlock("Intensiv-Wiederholung",result.missing)}`;if(result.passed)html+=`<div class="feedback-item ok"><strong>Aussprache freigeschaltet</strong>${audioRows(ex.expected)}</div>`;if(s.status==="verstanden")html+=`<div class="feedback-item ok"><strong>Nächstes Thema bereit</strong>Mit WEITER geht es zur nächsten Kategorie.</div>`;fb.innerHTML=html+renderFeedbackAction(result.passed);fb.classList.remove("hidden")}
function goNext(){const module=activeModule();const s=getModuleState(module);if(lastCheckedMode==="vocab"){if(!lastCheckedPassed){s.vocabVariant+=1;s.vocabSeed=nextSeed()}else{s.exerciseSeed=nextSeed()}}else if(!lastCheckedPassed){s.variant+=1;s.exerciseSeed=nextSeed()}else if(s.correctStreak>=1){const next=moduleIndex(module.id)+1;if(next<modules.length){state.activeModule=modules[next].id;const nextState=getModuleState(modules[next]);nextState.vocabSeed=nextSeed();nextState.exerciseSeed=nextSeed()}}lastCheckedPassed=null;lastCheckedMode=null;byId("answerInput").value="";byId("feedback").classList.add("hidden");saveState();render()}
function refreshVoices(){voices=(speechSynthesis?.getVoices?.()||[]).filter((v)=>/^sv/i.test(v.lang)||/swedish|svenska|bengt/i.test(v.name))}
function voice(){return voices[0]||null}
function speakSwedish(text,speed="normal"){if(!("speechSynthesis" in window)){alert("Dein Browser unterstützt keine Sprachausgabe.");return}refreshVoices();const v=voice();if(!v){alert("Keine schwedische Stimme gefunden. Installiere in Windows eine schwedische Sprache/Stimme oder nutze Edge/Chrome mit einer sv-SE Stimme.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="sv-SE";u.voice=v;u.rate=speed==="slow"?.72:.9;u.pitch=1;speechSynthesis.speak(u)}
function celebration(){const c=byId("celebration");c.classList.remove("fly");void c.offsetWidth;c.classList.add("fly");try{const ctx=new (window.AudioContext||window.webkitAudioContext)();[880,1175,1568].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;g.gain.value=.02;o.connect(g);g.connect(ctx.destination);o.start(ctx.currentTime+i*.08);o.stop(ctx.currentTime+i*.08+.25)})}catch{}}
async function copyChar(char,button){try{await navigator.clipboard.writeText(char);button.dataset.tooltip="copied";button.classList.add("copied");setTimeout(()=>{button.dataset.tooltip="copy";button.classList.remove("copied")},900)}catch{byId("answerInput").focus();document.execCommand("insertText",false,char)}}
byId("moduleList").addEventListener("click",(e)=>{const b=e.target.closest("[data-module]");if(!b||b.disabled)return;state.activeModule=b.dataset.module;lastCheckedPassed=null;lastCheckedMode=null;byId("feedback").classList.add("hidden");saveState();render()});
byId("vocabForm").addEventListener("submit",(e)=>{e.preventDefault();const m=activeModule();const r=checkVocab(m);applyVocab(r,m);lastCheckedPassed=r.passed;lastCheckedMode="vocab";render();showVocabFeedback(r);renderFlowButton()});
byId("answerForm").addEventListener("submit",(e)=>{e.preventDefault();const text=byId("answerInput").value.trim();if(!text)return;const m=activeModule();const ex=exercise(m);const r=checkAnswer(text,ex,m);const mastered=applyAnswer(r,m);lastCheckedPassed=r.passed;lastCheckedMode="exercise";render();showAnswerFeedback(r,m,ex);renderFlowButton();if(mastered)celebration()});
byId("nextBtn").addEventListener("click",goNext);byId("feedback").addEventListener("click",(e)=>{const flow=e.target.closest("[data-feedback-flow]");if(flow)return goNext();const speak=e.target.closest("[data-speak]");if(speak)speakSwedish(decodeURIComponent(speak.dataset.speak),speak.dataset.speed||"normal")});
document.querySelectorAll("[data-copy-char]").forEach((b)=>{b.addEventListener("click",()=>copyChar(b.dataset.copyChar,b));b.addEventListener("mouseenter",()=>copyChar(b.dataset.copyChar,b))});
byId("resetBtn").addEventListener("click",()=>{if(!confirm("Fortschritt wirklich zurücksetzen?"))return;localStorage.removeItem("svenska-a1-state");state=loadState();lastCheckedPassed=null;lastCheckedMode=null;byId("answerInput").value="";byId("feedback").classList.add("hidden");render()});
resetLegacy();refreshVoices();if("speechSynthesis" in window)speechSynthesis.onvoiceschanged=refreshVoices;render();
