const DATA_VERSION = "20260609-tala-a1plus-full-s1-10-audio";
const byId = (id) => document.getElementById(id);
const AUDIO_BASE_URL = (window.SVENSKA_AUDIO_BASE_URL || "audio").replace(/\/$/,"");
const baseModules = [
  ["avsnitt-0-start","Avsnitt 0: Kursstart","Tala svenska: Begrüßung, Name, Zahlen 0-6, Alphabet",["Hallo, ich heiße Jay.","Du heißt Stefan.","Ja, danke.","Nein, ich heiße Jay.","Auf Wiedersehen."],["Hej, jag heter Jay.","Du heter Stefan.","Ja, tack.","Nej, jag heter Jay.","Hej då."]],
  ["avsnitt-1-hej","Avsnitt 1.1: Begrüßen und vorstellen","Hejsan: Begrüßung, Name, Abschied",["Hallo!","Guten Morgen!","Wie heißt du?","Ich heiße Jay.","Nett, dich kennenzulernen."],["Hej!","God morgon!","Vad heter du?","Jag heter Jay.","Trevligt att träffas."]],
  ["avsnitt-1-origin","Avsnitt 1.2: Herkunft und Länder","Hejsan: varifrån, från, kommer, Personalpronomen",["Woher kommst du?","Ich komme aus der Schweiz.","Kommt ihr aus Schweden?","Nein, wir kommen aus Deutschland.","Sie kommt aus Malmö."],["Varifrån kommer du?","Jag kommer från Schweiz.","Kommer ni från Sverige?","Nej, vi kommer från Tyskland.","Hon kommer från Malmö."]],
  ["avsnitt-1-course","Avsnitt 1.3: Svenska i kursen","Hejsan: Kursanweisungen und erste Klassenraumwörter",["Lies den Dialog!","Schreib es auf!","Ich verstehe nicht.","Was bedeutet das?","Kannst du deutlicher sprechen?"],["Läs dialogen!","Skriv upp det!","Jag förstår inte.","Vad betyder det?","Kan du tala tydligare?"]],
  ["avsnitt-1-room","Avsnitt 1.4: En kurslokal","Hejsan: en/ett, unbestimmter Artikel, Dinge im Kursraum",["Was ist das?","Das ist ein Stift.","Das ist ein Heft.","Das ist eine Karte.","Das ist ein Tisch."],["Vad är det?","Det är en penna.","Det är ett block.","Det är en karta.","Det är ett bord."]],
  ["avsnitt-1-alphabet","Avsnitt 1.5: Alphabet und Zahlen 0-12","Hejsan: Alphabet, Abkürzungen, Grundzahlen",["Buchstabiere deinen Namen.","Acht plus vier ist zwölf.","Stockholm liegt in Schweden.","Wo liegt Malmö?","Malmö liegt in Schweden."],["Stava ditt namn.","Åtta plus fyra är tolv.","Stockholm ligger i Sverige.","Var ligger Malmö?","Malmö ligger i Sverige."]],
  ["avsnitt-1-review","Avsnitt 1: Mini-Test","Hejsan: Wiederholung aus Lernbuch und Übungsbuch",["Stell dich kurz vor.","Sage, woher du kommst.","Benenne einen Gegenstand im Kursraum.","Frage nach der Bedeutung.","Verabschiede dich."],["Jag heter Jay.","Jag kommer från Schweiz.","Det är en penna.","Vad betyder det?","Hej då."]],
  ["avsnitt-2-spelling","Avsnitt 2.1: Namen buchstabieren","Hej turist: förnamn, efternamn, stavar",["Wie buchstabiert man das?","Mein Vorname ist Jay.","Mein Nachname ist O'Farrell.","Kannst du den Namen wiederholen?","Das ist ein deutscher Name."],["Hur stavar man det?","Mitt förnamn är Jay.","Mitt efternamn är O'Farrell.","Kan du upprepa namnet?","Det är ett tyskt namn."]],
  ["avsnitt-2-tourist","Avsnitt 2.2: Touristinformation","Hej turist: Piktogramme, Orte, en/ett, bestimmter Artikel",["Gibt es hier einen Campingplatz?","Ja, den gibt es.","Wo liegt das Hotel?","Die Touristeninformation liegt hier.","Ich brauche eine Karte."],["Finns det en campingplats här?","Ja, det finns det.","Var ligger hotellet?","Turistbyrån ligger här.","Jag behöver en karta."]],
  ["avsnitt-2-article","Avsnitt 2.3: Bestimmter Artikel","Hej turist: campingplatsen, kartan, hotellet",["Wo liegt der Campingplatz?","Die Karte liegt hier.","Das Hotel ist groß.","Die Bushaltestelle ist dort.","Ich sehe den See."],["Var ligger campingplatsen?","Kartan ligger här.","Hotellet är stort.","Busshållplatsen ligger där.","Jag ser sjön."]],
  ["avsnitt-2-help","Avsnitt 2.4: Empfehlung und Auskunft","Hej turist: rekommenderar, tyvärr, hur långt",["Ich empfehle den Strand.","Leider gibt es hier kein Restaurant.","Wie weit ist es nach Halmstad?","Es sind zwei Meilen.","Danke für die Information."],["Jag rekommenderar stranden.","Tyvärr finns det ingen restaurang här.","Hur långt är det till Halmstad?","Det är två mil.","Tack för informationen."]],
  ["avsnitt-2-verbs","Avsnitt 2.5: Infinitiv und Präsens","Hej turist: Aktivitäten und Präsensformen",["Ich wandere in Schweden.","Sie besucht Freunde.","Er wohnt im Hotel.","Wir trinken Kaffee.","Sie schreiben eine Postkarte."],["Jag vandrar i Sverige.","Hon besöker vänner.","Han bor på hotell.","Vi dricker kaffe.","De skriver ett vykort."]],
  ["avsnitt-2-review","Avsnitt 2: Mini-Test","Hej turist: Name, Tourist-Info, Artikel, Präsens",["Frage nach einem Campingplatz.","Frage nach einer Karte.","Empfiehl eine Badestelle.","Sage, dass du mit dem Bus fährst.","Sage, was du im Urlaub machst."],["Finns det en campingplats här?","Har ni en karta?","Jag rekommenderar badplatsen.","Jag åker buss.","Jag vandrar i Sverige."]],
  ["avsnitt-3-phone","Avsnitt 3.1: Ett telefonsamtal","Mer kontakt: Telefon eröffnen, jemanden verlangen, verbinden",["Hallo, hier ist Jay.","Kann ich mit Jan sprechen?","Einen Augenblick bitte.","Wer ist das?","Ich rufe später wieder an."],["Hej, det är Jay.","Träffas Jan?","Ett ögonblick, tack.","Vem är det?","Jag ringer senare."]],
  ["avsnitt-3-smalltalk","Avsnitt 3.2: Hur mår du?","Mer kontakt: Befinden, Smalltalk, Gespräch beenden",["Wie geht es dir?","Mir geht es gut, danke.","Nicht so gut.","Ich bin müde.","Schönen Tag noch!"],["Hur mår du?","Jag mår bra, tack.","Inte så bra.","Jag är trött.","Ha en bra dag!"]],
  ["avsnitt-3-numbers","Avsnitt 3.3: Zahlen 13-1000","Mer kontakt: Telefonnummer, Hausnummer, Grundzahlen",["Meine Telefonnummer ist 070 345 89 32.","Die Hausnummer ist achtzehn.","Es kostet hundert Kronen.","Ich wohne in Malmö.","Kannst du die Nummer wiederholen?"],["Mitt telefonnummer är 070 345 89 32.","Husnumret är arton.","Det kostar hundra kronor.","Jag bor i Malmö.","Kan du upprepa numret?"]],
  ["avsnitt-3-contact","Avsnitt 3.4: Kontaktangaben und Wohnen","Mer kontakt: Adresse, E-Mail, Wohnform, Sprachen",["Was hast du für eine Adresse?","Ich wohne in einer Wohnung.","Meine E-Mail-Adresse ist jay@example.com.","Welche Sprachen sprichst du?","Ich spreche Deutsch und ein bisschen Schwedisch."],["Vad har du för adress?","Jag bor i en lägenhet.","Min mejladress är jay@example.com.","Vilka språk talar du?","Jag talar tyska och lite svenska."]],
  ["avsnitt-3-genitive","Avsnitt 3.5: Genitiv und Kurzantworten","Mer kontakt: Jans telefonnummer, ja det gör jag",["Das ist Jans Telefonnummer.","Das ist Evas E-Mail-Adresse.","Hast du eine Katze?","Ja, das habe ich.","Nein, das habe ich nicht."],["Det är Jans telefonnummer.","Det är Evas mejladress.","Har du en katt?","Ja, det har jag.","Nej, det har jag inte."]],
  ["avsnitt-3-review","Avsnitt 3: Mini-Test","Mer kontakt: Telefon, Befinden, Kontakt, Wohnen",["Beginne ein Telefongespräch.","Frage nach dem Befinden.","Gib deine Telefonnummer an.","Sage, wie du wohnst.","Antworte kurz auf eine Ja/Nein-Frage."],["Hej, det är Jay.","Hur mår du?","Mitt telefonnummer är 123.","Jag bor i en lägenhet.","Ja, det gör jag."]],
  ["avsnitt-4-money","Avsnitt 4.1: Vid uttagsautomaten","Varsågod: Geld, Karte, PIN, Preise",["Ich brauche Geld.","Ich bezahle mit Karte.","Ich verstehe den Code nicht.","Was kostet das?","Das kostet fünfundvierzig Kronen."],["Jag behöver pengar.","Jag betalar med kort.","Jag förstår inte koden.","Vad kostar det?","Det kostar fyrtiofem kronor."]],
  ["avsnitt-4-secondhand","Avsnitt 4.2: Secondhandbutik","Varsågod: Dinge kaufen, den/det, mögen",["Ich arbeite in einem Secondhandladen.","Man kann Kleidung kaufen.","Ich mag meinen Job.","Die Vase kostet zwanzig Kronen.","Ich nehme sie."],["Jag arbetar i en secondhandbutik.","Man kan köpa kläder.","Jag gillar mitt jobb.","Vasen kostar tjugo kronor.","Jag tar den."]],
  ["avsnitt-4-kiosk","Avsnitt 4.3: I kioskbutiken","Varsågod: Kiosk, etwas kaufen, Quittung",["Eine Postkarte, bitte.","Möchtest du noch etwas?","Nein danke, das ist gut so.","Willst du die Quittung?","Danke und tschüss."],["Ett vykort, tack.","Vill du ha något mer?","Nej tack, det är bra så.","Vill du ha kvittot?","Tack och hej."]],
  ["avsnitt-4-lunch","Avsnitt 4.4: Vad ska vi äta?","Varsågod: hungrig, törstig, lunch, vill ha",["Ich bin hungrig.","Ich bin durstig.","Ich möchte ein Glas Wasser.","Was willst du essen?","Ich nehme Fisch mit Kartoffeln."],["Jag är hungrig.","Jag är törstig.","Jag vill ha ett glas vatten.","Vad vill du äta?","Jag tar fisk med potatis."]],
  ["avsnitt-4-cafe","Avsnitt 4.5: På kafé","Varsågod: fika, einladen, lieber nehmen",["Ich lade dich ein.","Kann ich einen Kaffee bekommen?","Was sollen wir nehmen?","Ich nehme lieber einen Kuchen.","Danke sehr!"],["Jag bjuder.","Kan jag få en kaffe?","Vad ska vi ta?","Jag tar hellre en bakelse.","Tack så mycket!"]],
  ["avsnitt-4-modal","Avsnitt 4.6: Modalverben und Kurzantworten","Varsågod: vill, kan, måste, ska + Infinitiv",["Ich will eine Zeitung kaufen.","Ich muss arbeiten.","Kannst du Schwedisch sprechen?","Ja, das kann ich.","Nein, das muss ich nicht."],["Jag vill köpa en tidning.","Jag måste jobba.","Kan du tala svenska?","Ja, det kan jag.","Nej, det måste jag inte."]],
  ["avsnitt-4-review","Avsnitt 4: Mini-Test","Varsågod: Geld, Kiosk, Lunch, Café, Modalverben",["Frage nach einem Preis.","Kaufe etwas im Kiosk.","Sage, dass du hungrig bist.","Lade jemanden zum Kaffee ein.","Bilde einen Satz mit vill plus Infinitiv."],["Vad kostar det?","Ett vykort, tack.","Jag är hungrig.","Jag bjuder på kaffe.","Jag vill köpa en tidning."]],
  ["avsnitt-5-city","Avsnitt 5.1: På stan","Stadt, Orte und Institutionen in Kristianstad",["Kristianstad liegt in Südschweden.","In der Stadt gibt es ein Museum.","Das Krankenhaus liegt dort.","Ich sehe einen Platz und eine Kirche.","Das Einkaufszentrum ist modern.","Viele Geschäfte liegen im Zentrum."],["Kristianstad ligger i södra Sverige.","Det finns ett museum i staden.","Sjukhuset ligger där.","Jag ser ett torg och en kyrka.","Köpcentrumet är modernt.","Många butiker ligger i centrum."]],
  ["avsnitt-5-shops","Avsnitt 5.2: Affärer","Geschäfte, Institutionen und Einkaufen",["Ich gehe in die Apotheke.","Du kaufst Blumen im Blumengeschäft.","Wir kaufen Schuhe im Schuhgeschäft.","Gibt es eine Bank in der Nähe?","Der Lebensmittelladen ist geöffnet.","Ich suche eine Buchhandlung."],["Jag går till apoteket.","Du köper blommor i blomsteraffären.","Vi köper skor i skoaffären.","Finns det en bank i närheten?","Mataffären är öppen.","Jag letar efter en bokhandel."]],
  ["avsnitt-5-prepositions","Avsnitt 5.3: Prepositioner","i, mellan, framför, bakom, bredvid, mittemot",["Die Bank liegt neben der Apotheke.","Das Museum liegt gegenüber dem Rathaus.","Der Platz liegt zwischen der Kirche und dem Hotel.","Die Skulptur steht vor dem Theater.","Der Bahnhof liegt hinter dem Einkaufszentrum.","Das Café liegt rechts vom Kino."],["Banken ligger bredvid apoteket.","Museet ligger mittemot rådhuset.","Torget ligger mellan kyrkan och hotellet.","Skulpturen står framför teatern.","Stationen ligger bakom köpcentrumet.","Kaféet ligger till höger om bion."]],
  ["avsnitt-5-som","Avsnitt 5.4: Som","Relativpronomen som und kurze Beschreibungen",["Kristianstad ist eine Stadt, die viele Geschäfte hat.","Ich suche ein Café, das geöffnet ist.","Das ist eine Kirche, die alt ist.","Lasse kauft ein Eis, das fünfundzwanzig Kronen kostet.","Die Familie hat einen Hund, der Karo heißt.","Das ist ein Museum, das ich besuchen möchte."],["Kristianstad är en stad som har många affärer.","Jag letar efter ett kafé som är öppet.","Det är en kyrka som är gammal.","Lasse köper en glass som kostar tjugofem kronor.","Familjen har en hund som heter Karo.","Det är ett museum som jag vill besöka."]],
  ["avsnitt-5-directions","Avsnitt 5.5: Att hitta rätt","Nach dem Weg fragen und den Weg beschreiben",["Entschuldigung, wie komme ich zum Rathaus?","Gehen Sie geradeaus.","Nehmen Sie die erste Straße rechts.","Gehen Sie über den Platz.","Die Bibliothek liegt links.","Danke für die Hilfe."],["Ursäkta, hur kommer jag till rådhuset?","Gå rakt fram.","Ta första gatan till höger.","Gå över torget.","Biblioteket ligger till vänster.","Tack för hjälpen."]],
  ["avsnitt-5-review","Avsnitt 5: Mini-Test","På stan: Stadt, Geschäfte, Präpositionen, som, Weg",["Frage nach dem Weg zur Bank.","Beschreibe, wo das Museum liegt.","Sage, was man in einer Apotheke kauft.","Bilde einen Satz mit som.","Sage jemandem, dass er links abbiegen soll.","Sage, dass du im Zentrum einkaufst."],["Hur kommer jag till banken?","Museet ligger bredvid kyrkan.","Man köper medicin på apoteket.","Det är en stad som har många butiker.","Sväng till vänster.","Jag handlar i centrum."]],
  ["avsnitt-6-train","Avsnitt 6.1: Ombord på tåget","Zug, Fahrplan und Reisezeit",["Der Zug fährt um sieben Uhr.","Ich sitze im Zug.","Der Zugbegleiter kontrolliert die Fahrkarte.","Wann kommt der Zug in Gällivare an?","Wir machen eine Pause in Östersund.","Die Reise dauert viele Stunden."],["Tåget går klockan sju.","Jag sitter på tåget.","Tågvärden kontrollerar biljetten.","När kommer tåget till Gällivare?","Vi tar en paus i Östersund.","Resan tar många timmar."]],
  ["avsnitt-6-clock","Avsnitt 6.2: Vad är klockan?","Uhrzeit, Minuten, Viertel und halb",["Wie spät ist es?","Es ist Viertel nach acht.","Es ist halb sieben.","Es ist zehn vor sechs.","Der Unterricht beginnt um fünf nach neun.","Der Film endet um Viertel vor zehn."],["Vad är klockan?","Klockan är kvart över åtta.","Klockan är halv sju.","Klockan är tio i sex.","Lektionen börjar fem över nio.","Filmen slutar kvart i tio."]],
  ["avsnitt-6-weekdays","Avsnitt 6.3: En vanlig vecka","Wochentage und Tagesablauf",["Am Montag arbeite ich.","Am Dienstag habe ich Schwedischkurs.","Am Mittwoch esse ich Mittag um zwölf.","Am Donnerstag trainiere ich.","Am Freitag treffe ich Freunde.","Am Wochenende schlafe ich lange."],["På måndag jobbar jag.","På tisdag har jag svenskakurs.","På onsdag äter jag lunch klockan tolv.","På torsdag tränar jag.","På fredag träffar jag vänner.","På helgen sover jag länge."]],
  ["avsnitt-6-reflexive","Avsnitt 6.4: Reflexiva pronomen","mig, dig, sig, oss, er",["Ich wasche mich.","Du ziehst dich an.","Sie setzt sich in die Küche.","Wir freuen uns.","Zieht ihr euch warm an?","Die Kinder beeilen sich."],["Jag tvättar mig.","Du klär på dig.","Hon sätter sig i köket.","Vi gläder oss.","Kläder ni på er varmt?","Barnen skyndar sig."]],
  ["avsnitt-6-breakfast","Avsnitt 6.5: Frukost","Frühstück und Essgewohnheiten",["Zum Frühstück esse ich Joghurt.","Ich trinke Tee, nicht Kaffee.","Du isst eine Scheibe Brot mit Butter.","Wir essen Knäckebrot mit Honig.","Ich nehme ein Ei und Saft.","Was isst du zum Frühstück?"],["Till frukost äter jag yoghurt.","Jag dricker te, inte kaffe.","Du äter en skiva bröd med smör.","Vi äter knäckebröd med honung.","Jag tar ett ägg och juice.","Vad äter du till frukost?"]],
  ["avsnitt-6-appointment","Avsnitt 6.6: En tid","Termine buchen und Treffen vereinbaren",["Ich möchte einen Termin buchen.","Geht es nächste Woche?","Kannst du am Donnerstag um fünf?","Nein, leider geht das nicht.","Sollen wir uns am Montag treffen?","Ja, das passt gut."],["Jag vill boka en tid.","Går det nästa vecka?","Kan du på torsdag klockan fem?","Nej, tyvärr går det inte.","Ska vi träffas på måndag?","Ja, det passar bra."]],
  ["avsnitt-6-review","Avsnitt 6: Mini-Test","Zeit: Uhr, Woche, Frühstück, Reflexiv, Termin",["Sage, wie spät es ist.","Sage, wann du frühstückst.","Bilde einen Satz mit mig.","Vereinbare einen Termin am Donnerstag.","Sage, was du am Freitag machst.","Frage, wann der Zug fährt."],["Klockan är halv åtta.","Jag äter frukost klockan åtta.","Jag tvättar mig.","Ska vi boka en tid på torsdag?","På fredag träffar jag vänner.","När går tåget?"]],
  ["avsnitt-7-opening","Avsnitt 7.1: Öppettider","Öffnungszeiten und kurzer Einkauf",["Wann öffnet der Laden?","Der Laden öffnet um neun Uhr.","Er schließt um einundzwanzig Uhr.","Hat der Supermarkt sonntags geöffnet?","Wir gehen zu Willys.","Heute gibt es viele Kunden."],["När öppnar affären?","Affären öppnar klockan nio.","Den stänger klockan tjugoett.","Har stormarknaden öppet på söndagar?","Vi går till Willys.","Idag finns det många kunder."]],
  ["avsnitt-7-grocery","Avsnitt 7.2: Har vi ost hemma?","Lebensmittel und Einkaufsliste",["Haben wir Käse zu Hause?","Der Kaffee ist alle.","Wir müssen Milch kaufen.","Schreib eine Einkaufsliste.","Wir brauchen Kartoffeln und Zwiebeln.","Ich kaufe Bananen und Äpfel."],["Har vi ost hemma?","Kaffet är slut.","Vi måste köpa mjölk.","Skriv en inköpslista.","Vi behöver potatis och lök.","Jag köper bananer och äpplen."]],
  ["avsnitt-7-packages","Avsnitt 7.3: Förpackningar","Packungen, Mengen und Gewichte",["Ich möchte ein Kilo Kartoffeln.","Wir brauchen zwei Liter Milch.","Kauf eine Tüte Chips.","Ich nehme eine Flasche Öl.","Hast du eine Dose Tomaten?","Ein Paket Waschmittel kostet viel."],["Jag vill ha ett kilo potatis.","Vi behöver två liter mjölk.","Köp en påse chips.","Jag tar en flaska olja.","Har du en burk tomater?","Ett paket tvättmedel kostar mycket."]],
  ["avsnitt-7-chark","Avsnitt 7.4: Vid charkdisken","Theke, Fleisch, Wurst und höflich bestellen",["Ich möchte gekochten Schinken.","Haben Sie Räucherschinken?","Ein Hekto Salami, bitte.","Ich nehme ein halbes Kilo Hackfleisch.","Was kostet der Käse?","Das ist alles, danke."],["Jag vill ha kokt skinka.","Har ni rökt skinka?","Ett hekto salami, tack.","Jag tar ett halvt kilo köttfärs.","Vad kostar osten?","Det var allt, tack."]],
  ["avsnitt-7-plural","Avsnitt 7.5: Plural und Menge","Plural unbestimmt, många und mycket",["Ich kaufe viele Bananen.","Wir haben keine Äpfel.","Es gibt viele Kassen.","Wir brauchen viel Kaffee.","Im Laden gibt es lange Warteschlangen.","Ich kaufe drei Flaschen Wasser."],["Jag köper många bananer.","Vi har inga äpplen.","Det finns många kassor.","Vi behöver mycket kaffe.","I affären finns det långa köer.","Jag köper tre flaskor vatten."]],
  ["avsnitt-7-review","Avsnitt 7: Mini-Test","Einkaufen: Öffnungszeiten, Lebensmittel, Verpackung, Plural",["Frage nach den Öffnungszeiten.","Sage, dass ihr Milch braucht.","Bestelle etwas an der Theke.","Nutze många mit einem Pluralwort.","Nutze mycket mit einem Stoffwort.","Kaufe zwei Liter Wasser."],["När öppnar affären?","Vi behöver mjölk.","Jag vill ha kokt skinka, tack.","Det finns många kunder.","Vi behöver mycket kaffe.","Jag köper två liter vatten."]],
  ["avsnitt-8-holidays","Avsnitt 8.1: Helger och månader","Feiertage, Monate und Jahreszeiten",["Im Januar ist es oft kalt.","Im Frühling feiern viele Ostern.","Im Sommer ist Mittsommer wichtig.","Im Dezember feiern wir Weihnachten.","Schönes Wochenende!","Guten Rutsch ins neue Jahr!"],["I januari är det ofta kallt.","På våren firar många påsk.","På sommaren är midsommar viktigt.","I december firar vi jul.","Trevlig helg!","Gott nytt år!"]],
  ["avsnitt-8-date","Avsnitt 8.2: Datum och födelsedag","Datum, Ordinalzahlen und Geburtstag",["Welches Datum ist heute?","Heute ist der fünfte Juni.","Wann hast du Geburtstag?","Ich habe am vierundzwanzigsten August Geburtstag.","Herzlichen Glückwunsch zum Geburtstag!","Wir feiern am Samstag."],["Vilket datum är det idag?","Idag är det den femte juni.","När fyller du år?","Jag fyller år den tjugofjärde augusti.","Grattis på födelsedagen!","Vi firar på lördag."]],
  ["avsnitt-8-party","Avsnitt 8.3: Kursfest och semester","Planen, Urlaub und Einladungen",["Wann möchtest du Urlaub haben?","Ich möchte um Mittsommer herum Urlaub haben.","Wir planen ein Kursfest.","Kannst du am Freitag kommen?","Danke, gleichfalls.","Jetzt muss ich los."],["När vill du ha semester?","Jag vill ha semester runt midsommar.","Vi planerar en kursfest.","Kan du komma på fredag?","Tack detsamma.","Nu måste jag gå."]],
  ["avsnitt-8-years","Avsnitt 8.4: Årtal och historia","Jahreszahlen und historische Ereignisse",["Gustav Vasa wurde König im Jahr 1523.","Schweden hat am sechsten Juni Nationalfeiertag.","Birger Magnusson war ein König.","Das Jahr hat zwölf Monate.","Ich lese einen Text über Geschichte.","Wann regierte der König?"],["Gustav Vasa blev kung år femtonhundratjugotre.","Sverige har nationaldag den sjätte juni.","Birger Magnusson var en kung.","Året har tolv månader.","Jag läser en text om historia.","När regerade kungen?"]],
  ["avsnitt-8-preterite","Avsnitt 8.5: Preteritum","Vergangenheit mit regelmäßigen Verben",["Gestern arbeitete ich.","Lena parkte das Auto.","Wir wanderten im Wald.","Sie kaufte ein Geschenk.","Er rief seinen Freund an.","Am Wochenende spielten wir Tennis."],["Igår jobbade jag.","Lena parkerade bilen.","Vi vandrade i skogen.","Hon köpte en present.","Han ringde sin vän.","På helgen spelade vi tennis."]],
  ["avsnitt-8-midsommar","Avsnitt 8.6: Midsommar","Mittsommer, Traditionen und Festwörter",["Zu Mittsommer tanzen wir.","Wir essen Hering und Kartoffeln.","Viele tragen einen Blumenkranz.","Die Mittsommerstange steht auf der Wiese.","Wir singen ein Lied.","Es ist ein schwedisches Fest."],["På midsommar dansar vi.","Vi äter sill och potatis.","Många har en blomsterkrans.","Midsommarstången står på ängen.","Vi sjunger en sång.","Det är en svensk fest."]],
  ["avsnitt-8-review","Avsnitt 8: Mini-Test","Helg: Datum, Monate, Urlaub, Geschichte, Preteritum",["Frage nach dem Datum.","Sage, wann du Geburtstag hast.","Plane ein Kursfest.","Sage einen Satz im Präteritum.","Sage etwas über Mittsommer.","Wünsche ein schönes Wochenende."],["Vilket datum är det idag?","Jag fyller år den femte juni.","Vi planerar en kursfest.","Igår jobbade jag.","På midsommar dansar vi.","Trevlig helg!"]],
  ["avsnitt-9-rooms","Avsnitt 9.1: Hemma hos mig","Räume und Wohnung beschreiben",["Ich sehe ein Schlafzimmer.","Die Küche ist groß.","Im Wohnzimmer steht ein Sofa.","Das Badezimmer liegt neben dem Flur.","Wir haben einen Balkon.","Das Kinderzimmer ist klein."],["Jag ser ett sovrum.","Köket är stort.","I vardagsrummet står en soffa.","Badrummet ligger bredvid hallen.","Vi har en balkong.","Barnrummet är litet."]],
  ["avsnitt-9-furniture","Avsnitt 9.2: Inredning","Möbel und Positionen im Zimmer",["Rechts steht ein Bett.","Gegenüber dem Bett steht ein Sofa.","Vor dem Sofa steht ein Couchtisch.","Links vom Schreibtisch steht eine Lampe.","Im Zimmer liegt ein Teppich.","Die Garderobe steht hinter der Tür."],["Till höger står en säng.","Mittemot sängen står en soffa.","Framför soffan står ett soffbord.","Till vänster om skrivbordet står en lampa.","I rummet ligger en matta.","Garderoben står bakom dörren."]],
  ["avsnitt-9-family","Avsnitt 9.3: Familj och possessiv","Familie, Verwandte und Possessivpronomen",["Das ist meine Schwester.","Ist das dein Hund?","Hier ist sein Bruder.","Das ist ihre Mutter.","Unser Kind heißt Leo.","Ihre Wohnung ist schön."],["Det är min syster.","Är det din hund?","Här är hans bror.","Det är hennes mamma.","Vårt barn heter Leo.","Deras lägenhet är fin."]],
  ["avsnitt-9-imperative","Avsnitt 9.4: Glöm inte!","Imperativ, Nachrichten und kurze Bitten",["Füttere Sally am Morgen.","Schließ das Fenster im Wohnzimmer.","Mach das Licht aus.","Lies, bevor du gehst.","Ruf Dan Andersson an.","Hol die Post, bitte."],["Mata Sally på morgonen.","Stäng fönstret i vardagsrummet.","Släck ljuset.","Läs innan du går.","Ring Dan Andersson.","Hämta posten, tack."]],
  ["avsnitt-9-chores","Avsnitt 9.5: Hushållssysslor","Haushalt, Aufgaben und auch/nicht auch",["Ich koche und backe.","Du wäschst und bügelst.","Wir räumen die Küche auf.","Sie staubsaugt das Wohnzimmer.","Er leert die Spülmaschine.","Ich putze das Badezimmer nicht gern."],["Jag lagar mat och bakar.","Du tvättar och stryker.","Vi plockar undan i köket.","Hon dammsuger vardagsrummet.","Han tömmer diskmaskinen.","Jag gillar inte att rengöra badrummet."]],
  ["avsnitt-9-recipe","Avsnitt 9.6: Recept","Kochen, Backen und Küchenverben",["Schäle die Kartoffeln.","Schneide die Zwiebeln.","Mische alles in einer Schüssel.","Gieß Sahne darüber.","Backe den Kuchen im Ofen.","Nimm zwei Esslöffel Zucker."],["Skala potatisen.","Skär löken.","Blanda allt i en skål.","Häll grädde över.","Grädda kakan i ugnen.","Ta två matskedar socker."]],
  ["avsnitt-9-review","Avsnitt 9: Mini-Test","Hemma: Räume, Möbel, Familie, Imperativ, Haushalt",["Beschreibe dein Wohnzimmer.","Nutze ein Possessivpronomen.","Gib eine kurze Bitte im Imperativ.","Sage eine Haushaltstätigkeit.","Sage, wo ein Möbel steht.","Danke für die Hilfe."],["I vardagsrummet står en soffa.","Det är min syster.","Stäng fönstret, tack.","Jag dammsuger rummet.","Lampan står bredvid soffan.","Tack för hjälpen."]],
  ["avsnitt-10-transport","Avsnitt 10.1: Transportmedel","Verkehrsmittel und Wege",["Ich fahre mit dem Bus.","Du nimmst die Straßenbahn.","Er fährt Auto.","Sie geht zu Fuß.","Wir fahren mit dem Zug nach Göteborg.","Ich mag es, Fahrrad zu fahren."],["Jag åker buss.","Du tar spårvagnen.","Han kör bil.","Hon går till fots.","Vi åker tåg till Göteborg.","Jag gillar att cykla."]],
  ["avsnitt-10-hotel","Avsnitt 10.2: Hotellbokning","Hotel buchen und Informationen geben",["Ich möchte ein Einzelzimmer buchen.","Gibt es ein freies Doppelzimmer?","Hat das Hotel Frühstück?","Wir kommen am Freitag an.","Wie viel kostet das Zimmer?","Dann buche ich jetzt."],["Jag vill boka ett enkelrum.","Finns det ett ledigt dubbelrum?","Har hotellet frukost?","Vi kommer på fredag.","Hur mycket kostar rummet?","Då bokar jag nu."]],
  ["avsnitt-10-indefinite","Avsnitt 10.3: Någon, något, några","Indefinite Pronomen im Hotel",["Hat das Hotel einen Aufzug?","Nein, es hat keinen Aufzug.","Gibt es ein Schwimmbad?","Ja, es gibt ein Schwimmbad.","Hat das Hotel Tagungsräume?","Nein, es hat keine Tagungsräume."],["Har hotellet någon hiss?","Nej, det har ingen hiss.","Finns det någon pool?","Ja, det finns en pool.","Har hotellet några mötesrum?","Nej, det har inga mötesrum."]],
  ["avsnitt-10-complaint","Avsnitt 10.4: Klagomål","Beschwerden und demonstrative Pronomen",["Dieser Aufzug funktioniert nicht.","Dieses Zimmer ist zu kalt.","Das da ist nicht sauber.","Ich möchte das Zimmer wechseln.","Die Dusche ist kaputt.","Es tut mir leid, wir helfen sofort."],["Den här hissen fungerar inte.","Det här rummet är för kallt.","Det där är inte rent.","Jag vill byta rum.","Duschen är sönder.","Det var tråkigt, vi hjälper till direkt."]],
  ["avsnitt-10-weather","Avsnitt 10.5: Väder och vykort","Wetter, Postkarte, Reisebericht",["Es regnet heute.","Es schneit in Jokkmokk.","Das Wetter ist kalt, aber schön.","Wir schreiben eine Postkarte.","Gestern besuchten wir den Markt.","Das Hotel war sehr gut."],["Det regnar idag.","Det snöar i Jokkmokk.","Vädret är kallt men fint.","Vi skriver ett vykort.","Igår besökte vi marknaden.","Hotellet var mycket bra."]],
  ["avsnitt-10-vacation","Avsnitt 10.6: Semester på väg","Ferienarten und kurze Reiseerzählung",["Ich mache gern Stadturlaub.","Sie machen Campingurlaub im Sommer.","Wir fahren in den Skiurlaub.","Ich möchte eine Wanderreise machen.","Letztes Jahr reiste ich nach Schweden.","Die Reise war kurz, aber schön."],["Jag gillar att åka på stadssemester.","De campar på sommaren.","Vi åker på skidsemester.","Jag vill göra en vandringsresa.","Förra året reste jag till Sverige.","Resan var kort men fin."]],
  ["avsnitt-10-review","Avsnitt 10: Mini-Test","På väg: Verkehr, Hotel, Pronomen, Wetter, Urlaub",["Sage, wie du zur Arbeit kommst.","Buche ein Hotelzimmer.","Nutze någon in einer Frage.","Beschwere dich über das Zimmer.","Sage etwas über das Wetter.","Erzähle einen Satz über eine Reise."],["Jag åker buss till jobbet.","Jag vill boka ett rum.","Finns det någon hiss?","Rummet är för kallt.","Det regnar idag.","Förra året reste jag till Sverige."]]
];
const nounPacks = [
  [["en tavla","Wandtafel"],["ett bord","Tisch"],["en stol","Stuhl"],["en lampa","Lampe"],["en dörr","Tür"],["ett fönster","Fenster"],["en säng","Bett"],["en bok","Buch"],["en penna","Stift"],["ett papper","Papier"]],
  [["ett kök","Küche"],["ett rum","Zimmer"],["en soffa","Sofa"],["en hylla","Regal"],["en dator","Computer"],["en telefon","Telefon"],["en nyckel","Schlüssel"],["en väska","Tasche"],["en jacka","Jacke"],["en sko","Schuh"]],
  [["en mamma","Mutter"],["en pappa","Vater"],["en bror","Bruder"],["en syster","Schwester"],["ett barn","Kind"],["en familj","Familie"],["en vän","Freund"],["en kvinna","Frau"],["en man","Mann"],["ett namn","Name"]],
  [["en tallrik","Teller"],["ett glas","Glas"],["en kopp","Tasse"],["en sked","Löffel"],["en gaffel","Gabel"],["en kniv","Messer"],["bröd","Brot"],["mjölk","Milch"],["vatten","Wasser"],["kaffe","Kaffee"]],
  [["en buss","Bus"],["ett tåg","Zug"],["en bil","Auto"],["en cykel","Fahrrad"],["en gata","Straße"],["en station","Bahnhof"],["en biljett","Ticket"],["en karta","Karte"],["en stad","Stadt"],["ett hus","Haus"]]
];
function nounModule(pack,index){return {id:`nouns-${index+1}`,title:`Nomen-Voci ${index+1}`,tag:"A1 Nomen, Dinge und Alltag",tasks:pack.slice(0,6).map(([,de])=>`Schreibe: ${de}.`),expected:pack.slice(0,6).map(([sv])=>`${sv}.`),nounVocab:pack}}
function formatTask(task){return /^(Schreibe|Nutze|Frage|Antworte|Bilde|Beantworte|Ergänze|Prüfung):?/i.test(task)?task:`Schreibe: ${task}`}
const checkpointSets = [
  {title:"A1-Checkpoint 1",tag:"Prüfung: Begrüßung, Person, Fragen",pairs:[["Hallo!","Hej!"],["Ich heiße Jay.","Jag heter Jay."],["Wo wohnst du?","Var bor du?"],["Ich wohne in der Schweiz.","Jag bor i Schweiz."],["Ich spreche ein bisschen Schwedisch.","Jag talar lite svenska."],["Kannst du wiederholen?","Kan du upprepa?"]]},
  {title:"A1-Checkpoint 2",tag:"Prüfung: Familie, Besitz, Alltag",pairs:[["Ich habe eine Schwester.","Jag har en syster."],["Meine Mutter wohnt hier.","Min mamma bor här."],["Ich habe keinen Bruder.","Jag har ingen bror."],["Mein Kind spricht Deutsch.","Mitt barn talar tyska."],["Das Haus ist groß.","Huset är stort."],["Ich bin müde.","Jag är trött."]]},
  {title:"A1-Checkpoint 3",tag:"Prüfung: Zeit, Essen, Einkauf",pairs:[["Heute arbeite ich.","Idag jobbar jag."],["Es ist acht Uhr.","Klockan är åtta."],["Ich möchte Kaffee.","Jag vill ha kaffe."],["Was kostet das?","Vad kostar det?"],["Ich suche eine Jacke.","Jag letar efter en jacka."],["Ich nehme das.","Jag tar den."]]},
  {title:"A1-Checkpoint 4",tag:"Prüfung: Weg, Reise, Wohnen",pairs:[["Wo ist der Bahnhof?","Var ligger stationen?"],["Gehen Sie geradeaus.","Gå rakt fram."],["Ich möchte ein Ticket kaufen.","Jag vill köpa en biljett."],["Der Bus kommt um acht.","Bussen kommer klockan åtta."],["Ich wohne in einer Wohnung.","Jag bor i en lägenhet."],["Die Küche ist groß.","Köket är stort."]]},
  {title:"A1-Checkpoint 5",tag:"Prüfung: Wetter, Gesundheit, Grammatik",pairs:[["Es ist kalt heute.","Det är kallt idag."],["Ich habe Kopfschmerzen.","Jag har huvudvärk."],["Ich spreche nicht Schwedisch.","Jag talar inte svenska."],["Ich kann ein bisschen Schwedisch sprechen.","Jag kan tala lite svenska."],["Morgen lerne ich Schwedisch.","Imorgon läser jag svenska."],["Ich komme aus Zürich.","Jag kommer från Zürich."]]}
];
function checkpointModule(set,index){return {id:`checkpoint-${index+1}`,title:set.title,tag:set.tag,tasks:set.pairs.map(([de])=>`Prüfung: ${de}`),expected:set.pairs.map(([,sv])=>sv),checkpoint:true}}
const modules = baseModules.map(([id,title,tag,tasks,expected])=>({id,title,tag,tasks:tasks.map(formatTask),expected,exerciseSize:Math.max(tasks.length,5)}));
const extraWords = {
  "avsnitt-0":[["Hej","Hallo"],["Välkommen","Willkommen"],["Tack","Danke"],["Ja","Ja"],["Nej","Nein"],["Hej då","Auf Wiedersehen"],["jag","ich"],["du","du"],["heter","heiße"],["namn","Name"],["kurs","Kurs"],["lärare","Lehrer / Lehrerin"],["bra","gut"],["och","und"]],
  "avsnitt-1":[["Hejsan","Hallo"],["varifrån","woher"],["kommer från","kommt aus"],["Sverige","Schweden"],["Schweiz","Schweiz"],["en penna","Stift"],["en bok","Buch"],["ett bord","Tisch"],["en stol","Stuhl"],["arbetar","arbeitet"],["ligger","liegt"],["stad","Stadt"],["noll","null"],["tolv","zwölf"]],
  "avsnitt-2":[["turist","Tourist"],["turistbyrå","Touristeninformation"],["strand","Strand"],["semester","Urlaub"],["efternamn","Nachname"],["förnamn","Vorname"],["stavar","buchstabiert"],["hjälpa","helfen"],["rekommenderar","empfiehlt"],["tyvärr","leider"],["tack så mycket","vielen Dank"],["långt","weit"],["nära","nah"],["trevlig","schön / angenehm"]],
  "avsnitt-3":[["kontakt","Kontakt"],["telefon","Telefon"],["telefonnummer","Telefonnummer"],["tala med","sprechen mit"],["hur mår du","wie geht es dir"],["mår bra","geht es gut"],["bor","wohnt"],["lägenhet","Wohnung"],["adress","Adresse"],["e-post","E-Mail"],["språk","Sprache"],["svenska","Schwedisch"],["lite","ein bisschen"],["kort svar","Kurzantwort"]],
  "avsnitt-4":[["varsågod","bitte / gern"],["kiosk","Kiosk"],["kaffe","Kaffee"],["te","Tee"],["lunch","Mittagessen"],["betala","bezahlen"],["kostar","kostet"],["pris","Preis"],["pengar","Geld"],["vill ha","möchte haben"],["tycker om","mag"],["behöver","braucht"],["ska","soll / werde"],["något","etwas"]],
  "avsnitt-5":[["på stan","in der Stadt"],["en parkeringsplats","Parkplatz"],["en teater","Theater"],["en kyrka","Kirche"],["ett sjukhus","Krankenhaus"],["ett bibliotek","Bibliothek"],["en stormarknad","Supermarkt"],["en arena","Arena"],["ett museum","Museum"],["en skulptur","Skulptur"],["en station","Bahnhof"],["ett torg","Platz"],["ett köpcentrum","Einkaufszentrum"],["ett rådhus","Rathaus"],["en gågata","Fußgängerzone"],["en bank","Bank"],["ett apotek","Apotheke"],["en bokhandel","Buchhandlung"],["en blomsteraffär","Blumengeschäft"],["en skoaffär","Schuhgeschäft"],["en mataffär","Lebensmittelladen"],["bredvid","neben"],["mittemot","gegenüber"],["framför","vor"],["bakom","hinter"],["mellan","zwischen"],["rakt fram","geradeaus"],["till höger","nach rechts"],["till vänster","nach links"],["sväng","biege ab"],["som","der/die/das"],["hitta rätt","den richtigen Weg finden"]],
  "avsnitt-6":[["klockan","die Uhrzeit"],["en väckarklocka","Wecker"],["en minut","Minute"],["en kvart","Viertelstunde"],["en halvtimme","halbe Stunde"],["en timme","Stunde"],["ett dygn","Tag und Nacht"],["en vardag","Werktag"],["måndag","Montag"],["tisdag","Dienstag"],["onsdag","Mittwoch"],["torsdag","Donnerstag"],["fredag","Freitag"],["lördag","Samstag"],["söndag","Sonntag"],["en frukost","Frühstück"],["yoghurt","Joghurt"],["en skiva bröd","Scheibe Brot"],["smör","Butter"],["marmelad","Marmelade"],["ett knäckebröd","Knäckebrot"],["honung","Honig"],["ett ägg","Ei"],["juice","Saft"],["boka en tid","einen Termin buchen"],["passar","passt"],["skyndar sig","beeilt sich"],["klä på sig","sich anziehen"],["tvättar sig","wäscht sich"],["går upp","steht auf"]],
  "avsnitt-7":[["en ost","Käse"],["mjölk","Milch"],["en apelsin","Orange"],["en banan","Banane"],["ett äpple","Apfel"],["potatis","Kartoffeln"],["en lök","Zwiebel"],["en köttbulle","Fleischbällchen"],["en kassa","Kasse"],["en kö","Warteschlange"],["en kundvagn","Einkaufswagen"],["en inköpslista","Einkaufsliste"],["en nummerlapp","Nummerzettel"],["en charkdisk","Fleischtheke"],["en burk","Dose"],["ett paket","Paket"],["en kartong","Karton"],["en tub","Tube"],["en flaska","Flasche"],["en påse","Tüte"],["ett kilo","Kilo"],["en liter","Liter"],["ett gram","Gramm"],["en deciliter","Deziliter"],["ett hekto","Hektogramm"],["kokt skinka","gekochter Schinken"],["rökt skinka","geräucherter Schinken"],["köttfärs","Hackfleisch"],["många","viele"],["mycket","viel"],["inga","keine"]],
  "avsnitt-8":[["en helg","Wochenende"],["en månad","Monat"],["en årstid","Jahreszeit"],["vår","Frühling"],["sommar","Sommer"],["höst","Herbst"],["vinter","Winter"],["påsk","Ostern"],["jul","Weihnachten"],["nyår","Neujahr"],["midsommar","Mittsommer"],["en födelsedag","Geburtstag"],["ett datum","Datum"],["den femte","der fünfte"],["den tjugofjärde","der vierundzwanzigste"],["en kalender","Kalender"],["en present","Geschenk"],["en blomsterkrans","Blumenkranz"],["en midsommarstång","Mittsommerstange"],["en sång","Lied"],["en kung","König"],["en regent","Regent"],["historia","Geschichte"],["regerade","regierte"],["jobbade","arbeitete"],["köpte","kaufte"],["ringde","rief an"],["vandrade","wanderte"],["firar","feiert"],["grattis","Glückwunsch"]],
  "avsnitt-9":[["ett sovrum","Schlafzimmer"],["ett vardagsrum","Wohnzimmer"],["ett kök","Küche"],["ett badrum","Badezimmer"],["en hall","Flur"],["ett arbetsrum","Arbeitszimmer"],["ett barnrum","Kinderzimmer"],["en tvättstuga","Waschküche"],["en balkong","Balkon"],["en stol","Stuhl"],["en soffa","Sofa"],["ett skrivbord","Schreibtisch"],["ett soffbord","Couchtisch"],["en fåtölj","Sessel"],["en lampa","Lampe"],["en säng","Bett"],["en hylla","Regal"],["en garderob","Kleiderschrank"],["en tavla","Bild / Tafel"],["en matta","Teppich"],["en familj","Familie"],["en syster","Schwester"],["en bror","Bruder"],["en mamma","Mutter"],["en pappa","Vater"],["ett barn","Kind"],["min","mein"],["mitt","mein"],["mina","meine"],["stäng","schließ"],["mata","füttere"],["dammsuger","staubsaugt"]],
  "avsnitt-10":[["på väg","unterwegs"],["ett transportmedel","Verkehrsmittel"],["en bil","Auto"],["en buss","Bus"],["en spårvagn","Straßenbahn"],["en taxi","Taxi"],["ett tåg","Zug"],["en tunnelbana","U-Bahn"],["en motorcykel","Motorrad"],["en cykel","Fahrrad"],["ett flyg","Flugzeug"],["en färja","Fähre"],["ett enkelrum","Einzelzimmer"],["ett dubbelrum","Doppelzimmer"],["en hiss","Aufzug"],["ett garage","Garage"],["en pool","Schwimmbad"],["ett mötesrum","Tagungsraum"],["en rumsnyckel","Zimmerschlüssel"],["ett nyckelkort","Schlüsselkarte"],["en duschtvål","Duschgel"],["ett schampo","Shampoo"],["ett täcke","Bettdecke"],["en handduk","Handtuch"],["ett lakan","Bettlaken"],["en hårtork","Föhn"],["ett strykjärn","Bügeleisen"],["någon","irgendein"],["något","irgendein"],["några","einige"],["ingen","kein"],["inget","kein"],["inga","keine"],["väder","Wetter"],["det regnar","es regnet"],["det snöar","es schneit"]],
  start:[["Hej","Hallo"],["Tack","Danke"],["Ursäkta","Entschuldigung"],["Hej då","Auf Wiedersehen"],["God morgon","Guten Morgen"],["God kväll","Guten Abend"],["Vi ses","Wir sehen uns"],["Ja","Ja"],["Nej","Nein"],["Varsågod","Bitte / gern"],["Förlåt","Verzeihung"],["Okej","Okay"]],
  intro:[["jag","ich"],["du","du"],["han","er"],["hon","sie"],["det","es"],["vi","wir"],["ni","ihr / Sie"],["de","sie"],["Sverige","Schweden"],["Schweiz","Schweiz"],["bor","wohne"],["kommer från","komme aus"],["lite","ein bisschen"],["namn","Name"]],
  questions:[["Vad","Was"],["Var","Wo"],["Vem","Wer"],["Hur","Wie"],["Vilka","Welche"],["Kan","Kann"],["du","du"],["ni","ihr / Sie"],["fråga","Frage"],["svar","Antwort"],["språk","Sprache"],["svenska","Schwedisch"]],
  pronouns:[["jag","ich"],["du","du"],["han","er"],["hon","sie"],["det","es"],["vi","wir"],["ni","ihr"],["de","sie"],["är","bin / bist / ist"],["snäll","nett"],["trött","müde"],["här","hier"]],
  alphabet:[["bokstav","Buchstabe"],["stavas","wird buchstabiert"],["upprepa","wiederholen"],["långsamt","langsam"],["snälla","bitte"],["e-post","E-Mail"],["punkt","Punkt"],["snabel-a","At-Zeichen"],["förnamn","Vorname"],["efternamn","Nachname"]],
  languages:[["tyska","Deutsch"],["engelska","Englisch"],["svenska","Schwedisch"],["språk","Sprache"],["lär mig","lerne"],["talar","spreche"],["förstår","verstehe"],["skriver","schreibe"],["läser","lese"],["mycket","viel"],["lite","wenig / ein bisschen"]],
  family:[["en bror","Bruder"],["en syster","Schwester"],["en mamma","Mutter"],["en pappa","Vater"],["ett barn","Kind"],["en familj","Familie"],["en vän","Freund"],["min","mein / meine"],["din","dein / deine"],["ingen","kein"]],
  possessive:[["min","mein / meine"],["mitt","mein / meine"],["mina","meine"],["din","dein / deine"],["ditt","dein / deine"],["dina","deine"],["här","hier"],["hemma","zu Hause"],["ett barn","Kind"],["en mamma","Mutter"],["en pappa","Vater"]],
  work:[["arbetar","arbeite"],["jobbar","arbeite"],["ett arbete","Arbeit"],["ett företag","Unternehmen"],["transport","Transport"],["logistik","Logistik"],["kontor","Büro"],["kollega","Kollege"],["chef","Chef"],["idag","heute"]],
  articles:[["en bil","ein Auto"],["bilen","das Auto"],["ett hus","ein Haus"],["huset","das Haus"],["en bok","ein Buch"],["boken","das Buch"],["ett bord","ein Tisch"],["bordet","der Tisch"],["en dörr","eine Tür"],["dörren","die Tür"]],
  plural:[["ett barn","ein Kind"],["två barn","zwei Kinder"],["en vän","ein Freund"],["många vänner","viele Freunde"],["en bok","ein Buch"],["tre böcker","drei Bücher"],["inga barn","keine Kinder"],["många","viele"],["få","wenige"],["några","einige"]],
  adjectives:[["stor","groß"],["stort","groß"],["liten","klein"],["litet","klein"],["bra","gut"],["dålig","schlecht"],["trött","müde"],["snäll","nett"],["kall","kalt"],["varm","warm"]],
  day:[["äter","esse"],["dricker","trinke"],["jobbar","arbeite"],["läser","lerne / lese"],["sover","schlafe"],["går","gehe"],["kommer","komme"],["morgon","Morgen"],["kväll","Abend"],["frukost","Frühstück"]],
  time:[["klockan","Uhr"],["idag","heute"],["imorgon","morgen"],["igår","gestern"],["måndag","Montag"],["tisdag","Dienstag"],["onsdag","Mittwoch"],["vecka","Woche"],["år","Jahr"],["tid","Zeit"]],
  numbers:[["noll","null"],["ett","eins"],["två","zwei"],["tre","drei"],["fyra","vier"],["fem","fünf"],["sex","sechs"],["sju","sieben"],["åtta","acht"],["nio","neun"],["tio","zehn"],["hundra","hundert"]],
  food:[["vatten","Wasser"],["bröd","Brot"],["frukost","Frühstück"],["mjölk","Milch"],["kaffe","Kaffee"],["te","Tee"],["mat","Essen"],["en kopp","Tasse"],["ett glas","Glas"],["betala","bezahlen"]],
  shopping:[["letar efter","suche"],["en jacka","Jacke"],["blått","blau"],["dyrt","teuer"],["billigt","billig"],["storlek","Größe"],["hjälp","Hilfe"],["pengar","Geld"],["kvitto","Quittung"],["tar","nehme"]],
  directions:[["stationen","Bahnhof"],["rakt fram","geradeaus"],["vänster","links"],["höger","rechts"],["nära","nahe"],["långt","weit"],["gata","Straße"],["här","hier"],["där","dort"],["ligger","liegt"]],
  travel:[["buss","Bus"],["tåg","Zug"],["biljett","Ticket"],["stationen","Bahnhof"],["gata","Straße"],["stad","Stadt"],["karta","Karte"],["höger","rechts"],["vänster","links"],["nära","nahe"]],
  camping:[["en campingplats","Campingplatz"],["campingplatser","Campingplätze"],["ett tält","Zelt"],["två tält","zwei Zelte"],["en stuga","Hütte"],["stugor","Hütten"],["en badboll","Wasserball"],["badbollar","Wasserbälle"],["en strand","Strand"],["stränder","Strände"],["en sjö","See"],["sjöar","Seen"]],
  home:[["en lägenhet","Wohnung"],["ett rum","Zimmer"],["ett kök","Küche"],["ett badrum","Badezimmer"],["en säng","Bett"],["ett bord","Tisch"],["en stol","Stuhl"],["en lampa","Lampe"],["liten","klein"],["stor","groß"]],
  weather:[["väder","Wetter"],["kallt","kalt"],["varmt","warm"],["regnar","regnet"],["snöar","schneit"],["sol","Sonne"],["moln","Wolken"],["sommar","Sommer"],["vinter","Winter"],["idag","heute"]],
  health:[["huvudvärk","Kopfschmerzen"],["sjuk","krank"],["läkare","Arzt"],["mår","geht es"],["bra","gut"],["dåligt","schlecht"],["trött","müde"],["ont","Schmerzen"],["hjälp","Hilfe"],["behöver","brauche"]],
  inte:[["inte","nicht"],["talar inte","spreche nicht"],["kan inte","kann nicht"],["vill inte","will nicht"],["lär sig inte","lernt nicht"],["mycket","viel"],["svenska","Schwedisch"],["bo","wohnen"],["Zürich","Zürich"],["syster","Schwester"]],
  modal:[["kan","kann"],["vill","will / möchte"],["måste","muss"],["tala","sprechen"],["bo","wohnen"],["lära mig","lernen"],["resa","reisen"],["köpa","kaufen"],["hjälpa","helfen"],["lite","ein bisschen"]],
  wordorder:[["idag","heute"],["imorgon","morgen"],["på kvällen","am Abend"],["nu","jetzt"],["jobbar","arbeite"],["läser","lerne / lese"],["dricker","trinke"],["bor","wohne"],["verb","Verb"],["ordföljd","Wortstellung"]],
  prepositions:[["i","in"],["på","auf / bei"],["från","aus / von"],["till","nach / zu"],["med","mit"],["utan","ohne"],["hemma","zu Hause"],["företag","Unternehmen"],["Stockholm","Stockholm"],["Schweiz","Schweiz"]],
  past:[["igår","gestern"],["var","war"],["hade","hatte"],["gjorde","machte"],["jobbade","arbeitete"],["hemma","zu Hause"],["kaffe","Kaffee"],["frågade","fragte"],["köpte","kaufte"],["läste","las / lernte"]],
  future:[["imorgon","morgen"],["ska","werde"],["nästa vecka","nächste Woche"],["resa","reisen"],["köpa","kaufen"],["biljett","Ticket"],["lära mig","lernen"],["jobba","arbeiten"],["Sverige","Schweden"],["vill","möchte"]],
  imperative:[["hjälp mig","hilf mir"],["upprepa","wiederhole"],["tala långsamt","sprich langsam"],["skriv","schreib"],["öppna","öffne"],["stäng","schließe"],["lyssna","hör zu"],["läs","lies"],["kom","komm"],["gärna","gern / bitte"]],
  dialog:[["Hej","Hallo"],["Hur mår du?","Wie geht es dir?"],["Jag mår bra","Mir geht es gut"],["Och du?","Und dir?"],["Tack","Danke"],["Vi ses","Wir sehen uns"],["förlåt","Entschuldigung"],["ingen fara","kein Problem"],["ha det bra","mach's gut"],["hej då","auf Wiedersehen"]],
  a1review:[["presentera dig","stell dich vor"],["jag heter","ich heiße"],["jag bor","ich wohne"],["jag kommer från","ich komme aus"],["jag arbetar","ich arbeite"],["min familj","meine Familie"],["inte","nicht"],["kan","kann"],["vill","möchte"],["idag","heute"]]
};
const commonVocab = [["jag","ich"],["du","du"],["han","er"],["hon","sie"],["det","es"],["vi","wir"],["ni","ihr / Sie"],["de","sie"],["en bror","Bruder"],["en syster","Schwester"],["en mamma","Mutter"],["en pappa","Vater"],["ett barn","Kind"],["en vän","Freund"],["ett bord","Tisch"],["en säng","Bett"],["en lampa","Lampe"],["en dörr","Tür"],["ett fönster","Fenster"],["en bok","Buch"]];
const hints = ["Klingt nah am deutschen Satz - erst laut lesen, dann klicken.","Merke dir den Anfangsbuchstaben und sprich das Wort langsam.","Das Wort kommt gleich in der Aufgabe wieder vor.","Mini-Trick: baue daraus im Kopf einen kurzen Alltagssatz."];
const filler = [["och","und"],["inte","nicht"],["jag","ich"],["du","du"],["är","bin / bist / ist / sind"],["har","habe / hat"],["vill","will / möchte"],["kan","kann"],["idag","heute"],["imorgon","morgen"]];
const nounArticles = {
  penna:["en","Stift"],bok:["en","Buch"],block:["ett","Block / Heft"],karta:["en","Karte"],bord:["ett","Tisch"],stol:["en","Stuhl"],papper:["ett","Papier"],suddgummi:["ett","Radiergummi"],tavla:["en","Tafel"],väska:["en","Tasche"],lärobok:["en","Lehrbuch"],övningsbok:["en","Übungsbuch"],ord:["ett","Wort"],kurs:["en","Kurs"],kurslokal:["en","Kursraum"],kursdeltagare:["en","Kursteilnehmer"],kursledare:["en","Kursleiter"],
  namn:["ett","Name"],förnamn:["ett","Vorname"],efternamn:["ett","Nachname"],telefon:["en","Telefon"],mobil:["en","Handy"],telefonnummer:["ett","Telefonnummer"],nummer:["ett","Nummer"],adress:["en","Adresse"],mejladress:["en","E-Mail-Adresse"],hemsida:["en","Webseite"],riktnummer:["ett","Vorwahl"],postnummer:["ett","Postleitzahl"],hemnummer:["ett","Festnetznummer"],boxnummer:["ett","Postfach"],kontakt:["en","Kontakt"],språk:["ett","Sprache"],"e-post":["en","E-Mail"],
  campingplats:["en","Campingplatz"],restaurang:["en","Restaurant"],turistbyrå:["en","Touristeninformation"],turist:["en","Tourist"],semester:["en","Urlaub"],information:["en","Information"],broschyr:["en","Broschüre"],kommun:["en","Gemeinde"],mil:["en","Meile"],bil:["en","Auto"],buss:["en","Bus"],linje:["en","Linie"],busshållplats:["en","Bushaltestelle"],hållplats:["en","Haltestelle"],hotell:["ett","Hotel"],vandrarhem:["ett","Vandrarheim / Hostel"],kafé:["ett","Café"],kiosk:["en","Kiosk"],museum:["ett","Museum"],gymnasium:["ett","Gymnasium"],sjukhus:["ett","Krankenhaus"],golfbana:["en","Golfplatz"],badplats:["en","Badestelle"],vandringsled:["en","Wanderweg"],stugby:["en","Feriendorf"],bensinstation:["en","Tankstelle"],mack:["en","Tankstelle"],toalett:["en","Toilette"],strand:["en","Strand"],väg:["en","Weg"],cykel:["en","Fahrrad"],båt:["en","Boot"],man:["en","Mann"],kvinna:["en","Frau"],ryggsäck:["en","Rucksack"],sjö:["en","See"],älg:["en","Elch"],skylt:["en","Schild"],brygga:["en","Steg"],skog:["en","Wald"],husbil:["en","Wohnmobil"],lax:["en","Lachs"],kyrka:["en","Kirche"],
  mässa:["en","Messe"],möte:["ett","Treffen"],ögonblick:["ett","Augenblick"],kopp:["en","Tasse"],chef:["en","Chef"],företagare:["en","Unternehmer"],kollega:["en","Kollege"],gata:["en","Straße"],lägenhet:["en","Wohnung"],villa:["en","Villa / Haus"],radhus:["ett","Reihenhaus"],storstad:["en","Großstadt"],stad:["en","Stadt"],by:["en","Dorf"],samhälle:["ett","Gemeinde / Ort"],centrum:["ett","Zentrum"],förort:["en","Vorort"],trädgård:["en","Garten"],hus:["ett","Haus"],rum:["ett","Zimmer"],kök:["ett","Küche"],badrum:["ett","Badezimmer"],
  pengar:["pengar","Geld"],kod:["en","Code"],pin:["en","PIN"],kort:["ett","Karte"],kvitto:["ett","Quittung"],pris:["ett","Preis"],krona:["en","Krone"],secondhandbutik:["en","Secondhandladen"],butik:["en","Laden"],organisation:["en","Organisation"],grundare:["en","Gründer"],kläder:["kläder","Kleidung"],sak:["en","Sache"],bok:["en","Buch"],glas:["ett","Glas"],porslin:["ett","Porzellan"],möbel:["en","Möbelstück"],verktyg:["ett","Werkzeug"],tidning:["en","Zeitung"],läsk:["en","Limonade"],flaska:["en","Flasche"],vatten:["ett","Wasser"],glass:["en","Eis"],påse:["en","Tüte"],chips:["chips","Chips"],tuggummi:["ett","Kaugummi"],frimärke:["ett","Briefmarke"],godispåse:["en","Süßigkeitentüte"],äpple:["ett","Apfel"],banan:["en","Banane"],chokladkaka:["en","Schokoladentafel"],vykort:["ett","Postkarte"],lunch:["en","Lunch"],soppa:["en","Suppe"],korv:["en","Wurst"],potatis:["en","Kartoffel"],pannbiff:["en","Hacksteak"],lök:["en","Zwiebel"],torskfilé:["en","Dorschfilet"],schnitzel:["en","Schnitzel"],pizza:["en","Pizza"],vatten:["ett","Wasser"],te:["ett","Tee"],kaffe:["ett","Kaffee"],smörgås:["en","Sandwich"],bulle:["en","Hefeschnecke"],bakelse:["en","Törtchen"],
  parkeringsplats:["en","Parkplatz"],teater:["en","Theater"],stormarknad:["en","Supermarkt"],arena:["en","Arena"],skulptur:["en","Skulptur"],station:["en","Bahnhof"],torg:["ett","Platz"],köpcentrum:["ett","Einkaufszentrum"],rådhus:["ett","Rathaus"],gågata:["en","Fußgängerzone"],apotek:["ett","Apotheke"],bokhandel:["en","Buchhandlung"],blomsteraffär:["en","Blumengeschäft"],skoaffär:["en","Schuhgeschäft"],mataffär:["en","Lebensmittelladen"],fotoaffär:["en","Fotogeschäft"],resebyrå:["en","Reisebüro"],musikaffär:["en","Musikgeschäft"],sportaffär:["en","Sportgeschäft"],systembolag:["ett","Systembolaget"],bibliotek:["ett","Bibliothek"],bank:["en","Bank"],klockspel:["ett","Glockenspiel"],väg:["en","Weg"],korsning:["en","Kreuzung"],promenad:["en","Spaziergang"],trafikljus:["ett","Ampel"],
  väckarklocka:["en","Wecker"],damklocka:["en","Damenuhr"],herrklocka:["en","Herrenuhr"],ringklocka:["en","Klingel"],dörrklocka:["en","Türklingel"],klockradio:["en","Radiowecker"],stoppur:["ett","Stoppuhr"],stationsklocka:["en","Bahnhofsuhr"],minut:["en","Minute"],halvtimme:["en","halbe Stunde"],kvart:["en","Viertelstunde"],timme:["en","Stunde"],dygn:["ett","Tag und Nacht"],vecka:["en","Woche"],månad:["en","Monat"],år:["ett","Jahr"],dag:["en","Tag"],vardag:["en","Werktag"],frukost:["en","Frühstück"],skiva:["en","Scheibe"],knäckebröd:["ett","Knäckebrot"],honung:["en","Honig"],ägg:["ett","Ei"],tid:["en","Zeit"],
  ost:["en","Käse"],apelsin:["en","Orange"],köttbulle:["en","Fleischbällchen"],kassa:["en","Kasse"],kö:["en","Warteschlange"],kundvagn:["en","Einkaufswagen"],inköpslista:["en","Einkaufsliste"],nummerlapp:["en","Nummerzettel"],charkdisk:["en","Fleischtheke"],burk:["en","Dose"],paket:["ett","Paket"],kartong:["en","Karton"],tub:["en","Tube"],kilo:["ett","Kilo"],liter:["en","Liter"],gram:["ett","Gramm"],deciliter:["en","Deziliter"],hekto:["ett","Hektogramm"],räka:["en","Garnele"],kaviar:["en","Kaviar"],marmelad:["en","Marmelade"],olja:["en","Öl"],mjöl:["ett","Mehl"],lättöl:["ett","Leichtbier"],skinka:["en","Schinken"],köttfärs:["en","Hackfleisch"],recept:["ett","Rezept"],tomat:["en","Tomate"],
  helg:["en","Wochenende"],påsk:["en","Ostern"],jul:["en","Weihnachten"],nyår:["ett","Neujahr"],pingst:["en","Pfingsten"],årstid:["en","Jahreszeit"],vår:["en","Frühling"],sommar:["en","Sommer"],höst:["en","Herbst"],vinter:["en","Winter"],födelsedag:["en","Geburtstag"],datum:["ett","Datum"],kalender:["en","Kalender"],present:["en","Geschenk"],blombukett:["en","Blumenstrauß"],parfym:["en","Parfüm"],biobiljett:["en","Kinokarte"],nationaldag:["en","Nationalfeiertag"],flaggdag:["en","Flaggentag"],kung:["en","König"],regent:["en","Regent"],historia:["en","Geschichte"],kursfest:["en","Kursfest"],midsommarstång:["en","Mittsommerstange"],blomsterkrans:["en","Blumenkranz"],folkdräkt:["en","Volkstracht"],folkdans:["en","Volkstanz"],snapsvisa:["en","Schnapslied"],jordgubbe:["en","Erdbeere"],sång:["en","Lied"],
  sovrum:["ett","Schlafzimmer"],vardagsrum:["ett","Wohnzimmer"],hall:["en","Flur"],arbetsrum:["ett","Arbeitszimmer"],barnrum:["ett","Kinderzimmer"],tvättstuga:["en","Waschküche"],balkong:["en","Balkon"],skrivbord:["ett","Schreibtisch"],soffbord:["ett","Couchtisch"],fåtölj:["en","Sessel"],hylla:["en","Regal"],garderob:["en","Kleiderschrank"],matta:["en","Teppich"],spegel:["en","Spiegel"],kudde:["en","Kissen"],filt:["en","Decke"],ljusstake:["en","Kerzenständer"],gardin:["en","Vorhang"],färg:["en","Farbe"],familj:["en","Familie"],fru:["en","Ehefrau"],förälder:["en","Elternteil"],son:["en","Sohn"],dotter:["en","Tochter"],morfar:["en","Großvater mütterlicherseits"],farmor:["en","Großmutter väterlicherseits"],sambo:["en","Lebenspartner"],hund:["en","Hund"],katt:["en","Katze"],fönster:["ett","Fenster"],ljus:["ett","Licht"],diskmaskin:["en","Spülmaschine"],städhjälp:["en","Putzhilfe"],hushåll:["ett","Haushalt"],syssla:["en","Aufgabe"],bakplåt:["en","Backblech"],matsked:["en","Esslöffel"],tesked:["en","Teelöffel"],grädde:["en","Sahne"],ansjovis:["en","Anchovis"],sallad:["en","Salat"],
  transportmedel:["ett","Verkehrsmittel"],spårvagn:["en","Straßenbahn"],taxi:["en","Taxi"],tunnelbana:["en","U-Bahn"],motorcykel:["en","Motorrad"],sittplatsbiljett:["en","Sitzplatzkarte"],spår:["ett","Gleis"],färja:["en","Fähre"],hytt:["en","Kabine"],flyg:["ett","Flugzeug"],flygplats:["en","Flughafen"],läsplatta:["en","Tablet"],sevärdhet:["en","Sehenswürdigkeit"],wifi:["ett","WLAN"],pool:["en","Schwimmbad"],hiss:["en","Aufzug"],garage:["ett","Garage"],mötesrum:["ett","Tagungsraum"],enkelrum:["ett","Einzelzimmer"],dubbelrum:["ett","Doppelzimmer"],rumsnyckel:["en","Zimmerschlüssel"],nyckelkort:["ett","Schlüsselkarte"],duschtvål:["en","Duschgel"],schampo:["ett","Shampoo"],täcke:["ett","Bettdecke"],handduk:["en","Handtuch"],lakan:["ett","Bettlaken"],tvål:["en","Seife"],hårtork:["en","Föhn"],strykjärn:["ett","Bügeleisen"],strykbräda:["en","Bügelbrett"],vattenkokare:["en","Wasserkocher"],reception:["en","Rezeption"],utsikt:["en","Aussicht"],park:["en","Park"],väder:["ett","Wetter"],snö:["en","Schnee"],sol:["en","Sonne"],regn:["ett","Regen"],marknad:["en","Markt"],renskinn:["ett","Rentierfell"],konsthantverk:["ett","Kunsthandwerk"],ishotell:["ett","Eishotel"],semesterresa:["en","Urlaubsreise"],vandringssemester:["en","Wanderurlaub"],campingsemester:["en","Campingurlaub"],stugsemester:["en","Hüttenurlaub"],skidsemester:["en","Skiurlaub"],cykelsemester:["en","Fahrradurlaub"],båtsemester:["en","Bootsurlaub"],ridsemester:["en","Reiturlaub"],stadssemester:["en","Städteurlaub"],tältsemester:["en","Zelturlaub"],strandsemester:["en","Strandurlaub"],solsemester:["en","Sonnenurlaub"]
};
const germanEineNouns = new Set(["syster","mamma","lampa","dörr","karta","tavla","väska","adress","mejladress","hemsida","e-post","turistbyrå","information","broschyr","kommun","mil","linje","busshållplats","hållplats","bensinstation","mack","toalett","kvinna","kyrka","mässa","kopp","gata","lägenhet","villa","storstad","stad","trädgård","pin","kort","kvitto","krona","organisation","sak","tidning","läsk","flaska","påse","godispåse","banan","chokladkaka","vykort","soppa","korv","potatis","lök","pizza","bulle","skulptur","gågata","bank","apotek","bokhandel","resebyrå","arena","damklocka","herrklocka","ringklocka","dörrklocka","stoppur","stationsklocka","minut","halvtimme","kvart","timme","vecka","månad","tid","apelsin","kö","kassa","inköpslista","charkdisk","burk","tub","räka","marmelad","tomat","årstid","historia","biobiljett","midsommarstång","folkdräkt","jordgubbe","tvättstuga","färg","familj","fru","dotter","diskmaskin","städhjälp","syssla","grädde","spårvagn","tunnelbana","sittplatsbiljett","färja","hytt","sevärdhet","garage","nyckelkort","frimärke","tvål","reception","utsikt","sol","semesterresa"]);
function audioRange(kind,start,end){const cfg={LB1:["MP3%20TSA1Plus%20LB1","TSA1_LB_1_"],LB2:["MP3%20TSA1Plus%20LB2","TSA1_LB_2_"],UB:["MP3%20TSA1Plus%20UB","TSA1_UB_"]}[kind];return Array.from({length:end-start+1},(_,i)=>{const nr=start+i;return {label:`${kind} Track ${nr}`,src:`${AUDIO_BASE_URL}/${cfg[0]}/${cfg[1]}${nr}.mp3`}})}
const bookAudio = {
  "avsnitt-0": audioRange("LB1",1,7),
  "avsnitt-1": [...audioRange("LB1",8,19),...audioRange("UB",1,2)],
  "avsnitt-2": [...audioRange("LB1",20,27),...audioRange("UB",3,5)],
  "avsnitt-3": [...audioRange("LB1",28,39),...audioRange("UB",6,13)],
  "avsnitt-4": [...audioRange("LB1",40,51),...audioRange("UB",14,18)],
  "avsnitt-5": [...audioRange("LB2",1,9),...audioRange("UB",19,20)],
  "avsnitt-6": [...audioRange("LB2",10,18),...audioRange("UB",21,27)],
  "avsnitt-7": [...audioRange("LB2",19,23),...audioRange("UB",28,29)],
  "avsnitt-8": [...audioRange("LB2",24,35),...audioRange("UB",30,32)],
  "avsnitt-9": [...audioRange("LB2",36,43),...audioRange("UB",33,40)],
  "avsnitt-10": [...audioRange("LB2",44,56),...audioRange("UB",41,45)]
};
const roastMessages = ["Hier hast du verkackt. Aber immerhin auf Schwedisch fast elegant.","Das war sprachlich ein Unfall mit Warnweste. Neuer Versuch.","Autsch. Dein Satz braucht weniger Drama und mehr Grammatik.","Knapp daneben ist auch vorbei. Wir schleifen das jetzt rein."];
const winMessages = ["Sauber. Das klingt langsam nach echtem Schwedisch.","Sehr gut. Gehirn hat heute Dienst.","Passt. Weiter, bevor du dich zu sehr feierst.","Stark. Das Thema ist nicht mehr dein Gegner."];
const coachRules = [
  {key:"ja-jag",pattern:/\bja\s+(heter|bor|kommer|talar|kan|vill|har|arbetar|jobbar|dricker|äter|läser)\b/i,fix:"jag",explain:"Du brauchst jag = ich. Ja bedeutet nur ja."},
  {key:"talar-tala",pattern:/\bjag\s+tala\b/i,fix:"Jag talar ...",explain:"Ohne kan/vill brauchst du Präsens: talar. Mit kan/vill kommt die Grundform: kan tala, vill tala."},
  {key:"bor-bo",pattern:/\bjag\s+bo\b/i,fix:"Jag bor ...",explain:"Ohne kan/vill brauchst du Präsens: bor. Mit kan/vill: vill bo, kan bo."},
  {key:"kan-vill-form",pattern:/\b(kan|vill)\s+(talar|bor|arbetar|dricker|äter|läser)\b/i,fix:"kan/vill + Grundform",explain:"Nach kan/vill steht die Grundform: tala, bo, arbeta, dricka, äta, läsa."},
  {key:"inte-position",pattern:/\b(jag|du|han|hon|vi|ni|de)\s+inte\s+(talar|bor|har|arbetar|jobbar|dricker|äter|läser|kan|vill)\b/i,fix:"inte nach dem ersten Verb",explain:"inte steht im Hauptsatz nach dem ersten Verb: Jag talar inte. Jag kan inte tala."},
  {key:"svenska-spelling",pattern:/\b(svenksa|svneksa|svensk)\b/i,fix:"svenska",explain:"Schwedisch heißt svenska."},
  {key:"mycket-spelling",pattern:/\bmacket\b/i,fix:"mycket",explain:"viel heißt mycket."},
  {key:"finns-spelling",pattern:/\b(fins|finnd)\b/i,fix:"finns",explain:"Es heißt finns: Det finns ... / Finns det ...?"},
  {key:"arbetar-spelling",pattern:/\barbeter\b/i,fix:"arbetar",explain:"arbeiten heißt arbetar."},
  {key:"jobbar-spelling",pattern:/\bjobber\b/i,fix:"jobbar",explain:"jobben/arbeiten heißt jobbar."},
  {key:"dricker-spelling",pattern:/\bdryckar\b/i,fix:"dricker",explain:"trinken heißt dricker."},
  {key:"företag-spelling",pattern:/\bfäretag\b/i,fix:"företag",explain:"Unternehmen heißt företag."},
  {key:"preposition-i",pattern:/\bin\s+(Schweiz|Sverige|Zürich|Volketswil|Stockholm)\b/i,fix:"i",explain:"Das deutsche in wird auf Schwedisch hier i: i Schweiz, i Sverige."},
  {key:"preposition-med",pattern:/\bmit\b/i,fix:"med",explain:"mit heißt med: Jag arbetar med transport."}
];
const pluralPairs = [
  ["biljett","biljetter"],["station","stationer"],["ryggsäck","ryggsäckar"],["restaurang","restauranger"],["karta","kartor"],["stuga","stugor"],["strand","stränder"],["sjö","sjöar"],["buss","bussar"],["tält","tält"],["hotell","hotell"],["tåg","tåg"]
];
const defaultState = { activeModule: "avsnitt-0-start", today: 0, totalErrors: 0, errors: {}, patterns: {}, modules: {} };
let state = loadState();
let lastCheckedPassed = null;
let lastCheckedMode = null;
let voices = [];
function loadState(){try{return {...structuredClone(defaultState),...(JSON.parse(localStorage.getItem("svenska-a1-state"))||{})}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem("svenska-a1-state",JSON.stringify(state));localStorage.setItem("svenska-a1-build",DATA_VERSION)}
function resetLegacy(){if(localStorage.getItem("svenska-a1-build")!==DATA_VERSION){localStorage.removeItem("svenska-a1-state");localStorage.setItem("svenska-a1-build",DATA_VERSION);state=structuredClone(defaultState);saveState()}}
function getModuleState(module){state.modules[module.id]={vocabStreak:0,correctStreak:0,status:"unsicher",variant:0,vocabVariant:0,vocabSeed:Date.now(),exerciseSeed:Date.now()+17,attempts:0,...(state.modules[module.id]||{})};return state.modules[module.id]}
function moduleIndex(id){return modules.findIndex((m)=>m.id===id)}
function isUnlocked(index){return index===0||modules.slice(0,index).every((m)=>getModuleState(m).status==="verstanden")}
function activeModule(){let index=moduleIndex(state.activeModule);if(index<0||!isUnlocked(index)){index=modules.findIndex((_,i)=>isUnlocked(i));state.activeModule=modules[Math.max(0,index)].id}return modules.find((m)=>m.id===state.activeModule)||modules[0]}
function normalize(text){return text.toLowerCase().replace(/[.,!?]/g,"").replace(/\s+/g," ").trim()}
function strip(text){return text.replace(/[.,!?]/g,"").trim()}
function taskGerman(task){return strip(task.replace(/^Schreibe:\s*/,"").replace(/^Zusatz:\s*Schreibe\s*/,"").replace(/^Prüfung:\s*/,"").replace(/^Frage:\s*/,"").replace(/^Antworte:\s*/,"").replace(/^"/,"").replace(/"$/,""))}
function nextSeed(){return Math.floor(Date.now()+Math.random()*1000000)}
function seededRandom(seed){let value=seed%2147483647;if(value<=0)value+=2147483646;return()=>{value=value*16807%2147483647;return(value-1)/2147483646}}
function shuffled(items,seed){const random=seededRandom(seed);const list=[...items];for(let i=list.length-1;i>0;i-=1){const j=Math.floor(random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function sectionKey(id){return id.match(/^(avsnitt-\d+)/)?.[1]||id}
function germanIndefiniteArticle(base){return germanEineNouns.has(base)?"eine":"ein"}
function withGermanArticle(sv,de){const raw=strip(String(sv||""));const match=raw.toLowerCase().match(/^(en|ett)\s+(.+)$/);if(!match)return de;const base=match[2];const entry=nounArticles[base];const german=(entry?.[1]||de||"").trim();if(!german||/^(ein|eine|einen|einem|einer)\b/i.test(german))return german;return `${germanIndefiniteArticle(base)} ${german}`}
function withNounArticle([sv,de]){const raw=strip(String(sv||""));const key=raw.toLowerCase();if(!raw)return [sv,de];if(/^(en|ett)\s+/i.test(raw))return [raw.toLowerCase(),withGermanArticle(raw,de)];if(raw.includes(" "))return [sv,de];const entry=nounArticles[key];if(!entry)return [sv,de];const [article,german]=entry;return article==="en"||article==="ett"?[`${article} ${key}`,withGermanArticle(`${article} ${key}`,german)]:[key,de||german]}
function getVocab(module){const phraseVocab=module.expected.map((sentence,index)=>[strip(sentence),taskGerman(module.tasks[index]||guessGerman(strip(sentence)))]);const fromExpected=module.expected.flatMap((sentence)=>strip(sentence).split(" ")).filter((w)=>w.length>1).map((sv)=>withNounArticle([sv,guessGerman(sv)])).filter(([,de])=>de);const nounVocab=module.nounVocab||[];const merged=[...nounVocab,...(extraWords[sectionKey(module.id)]||[]),...(extraWords[module.id]||[]),...phraseVocab,...fromExpected,...commonVocab,...filler].map(withNounArticle);const seen=new Set();return merged.filter(([sv,de])=>{const key=sv.toLowerCase();if(!de||seen.has(key))return false;seen.add(key);return true}).slice(0,28).map(([sv,de],i)=>({sv,de,hint:hints[i%hints.length]}))}
function guessGerman(sv){const map={Hej:"Hallo","Hej då":"Auf Wiedersehen",Tack:"Danke","Ursäkta":"Entschuldigung","God morgon":"Guten Morgen","God kväll":"Guten Abend","Vi ses":"Wir sehen uns",Ja:"Ja",Nej:"Nein","Varsågod":"Bitte / gern",Förlåt:"Verzeihung",Jag:"Ich",jag:"ich",Du:"Du",du:"du",Han:"Er",han:"er",Hon:"Sie",hon:"sie",det:"es",Vi:"Wir",vi:"wir",De:"Sie",de:"sie",Ni:"Ihr / Sie",ni:"ihr / Sie",heter:"heiße",kommer:"komme",från:"aus",bor:"wohne",talar:"spreche",svenska:"Schwedisch",tyska:"Deutsch",engelska:"Englisch",är:"bin / bist / ist / sind",snäll:"nett",trött:"müde",Schweiz:"Schweiz",Sverige:"Schweden",har:"habe / hat",inte:"nicht",vill:"will / möchte",kan:"kann",lära:"lernen",läser:"lerne / lese",mig:"mich / mir",sig:"sich",lite:"ein bisschen",mycket:"viel",kaffe:"Kaffee",barn:"Kind / Kinder",familj:"Familie",syster:"Schwester",bror:"Bruder",mamma:"Mutter",pappa:"Vater",vän:"Freund",bil:"Auto",Bilen:"das Auto",hus:"Haus",Huset:"das Haus",frukost:"Frühstück",vatten:"Wasser",bröd:"Brot",mjölk:"Milch",te:"Tee",mat:"Essen",biljett:"Ticket",stationen:"Bahnhof",gata:"Straße",stad:"Stadt",karta:"Karte",höger:"rechts",vänster:"links",nära:"nahe",idag:"heute",imorgon:"morgen",åtta:"acht",klockan:"Uhr",kostar:"kostet",kronor:"Kronen",tavla:"Wandtafel",bord:"Tisch",stol:"Stuhl",lampa:"Lampe",dörr:"Tür",fönster:"Fenster",säng:"Bett",bok:"Buch",penna:"Stift",papper:"Papier",kök:"Küche",rum:"Zimmer",soffa:"Sofa",hylla:"Regal",dator:"Computer",telefon:"Telefon",nyckel:"Schlüssel",väska:"Tasche",jacka:"Jacke",sko:"Schuh",tallrik:"Teller",glas:"Glas",kopp:"Tasse",sked:"Löffel",gaffel:"Gabel",kniv:"Messer",cykel:"Fahrrad"};return map[sv]||""}
function getVocabRound(module){const s=getModuleState(module);return shuffled(getVocab(module),s.vocabSeed+s.vocabVariant*97).slice(0,10)}
function unique(list){return [...new Set(list.filter(Boolean))]}
function getChoices(correct,module,index=0){const s=getModuleState(module);const all=unique([...getVocab(module),...filler.map(([sv,de])=>({sv,de}))].map((x)=>x.de).filter((de)=>de!==correct.de));return shuffled([correct.de,...shuffled(all,s.vocabSeed+index*31).slice(0,3)],s.vocabSeed+index*53)}
function exercise(module){const s=getModuleState(module);const basePairs=module.tasks.map((task,index)=>({task,expected:module.expected[index]}));const targetSize=module.checkpoint?6:(module.exerciseSize||5);const extras=shuffled(getVocab(module).filter((item)=>!module.expected.some((sentence)=>normalize(sentence).includes(normalize(item.sv)))),s.exerciseSeed+s.variant*131).slice(0,Math.max(0,targetSize-basePairs.length)).map((item)=>({task:`Zusatz: Schreibe "${item.de}".`,expected:item.sv}));const round=shuffled([...basePairs,...extras],s.exerciseSeed+s.variant*173).slice(0,targetSize);return {tasks:round.map((item)=>item.task),expected:round.map((item)=>item.expected)}}
function render(){const module=activeModule();const s=getModuleState(module);const vocab=s.vocabStreak<1;byId("moduleTag").textContent=module.tag;byId("moduleTitle").textContent=module.title;byId("topicStatus").textContent=vocab?`Voci ${s.vocabStreak}/1`:s.status;byId("difficulty").textContent=vocab?"Voci":"A1";byId("todayCount").textContent=state.today;byId("masteredCount").textContent=Object.values(state.modules).filter((m)=>m.status==="verstanden").length;byId("errorCount").textContent=state.totalErrors;renderModules();if(vocab){byId("taskTitle").textContent=`Voci vor "${module.title}"`;byId("taskList").innerHTML="<li>Beantworte 10 Wörter fehlerfrei.</li><li>Erst danach wird die Satzübung freigeschaltet.</li>"+bookAudioPanel(module);byId("answerForm").classList.add("hidden");byId("vocabForm").classList.remove("hidden");renderVocab(module)}else{const ex=exercise(module);byId("taskTitle").textContent=module.checkpoint?"A1-Checkpoint: gemischte Prüfung.":"Übung: ein längerer Durchgang.";byId("taskList").innerHTML=ex.tasks.map((t)=>`<li>${t}</li>`).join("")+bookAudioPanel(module);byId("vocabForm").classList.add("hidden");byId("answerForm").classList.remove("hidden")}renderFlowButton()}
function renderModules(){byId("moduleList").innerHTML=modules.map((m,i)=>{const s=getModuleState(m);const locked=!isUnlocked(i);return `<button class="module-button${m.id===state.activeModule?" active":""}${s.status==="verstanden"?" mastered":""}${locked?" locked":""}" data-module="${m.id}" type="button" ${locked?"disabled":""}>${m.title}<span>${locked?"Gesperrt · ":""}Voci ${s.vocabStreak}/1 · Übung ${Math.min(s.correctStreak,1)}/1 · ${s.status}</span></button>`}).join("")}
function renderVocab(module){const items=getVocabRound(module);byId("vocabForm").innerHTML=items.map((item,i)=>`<div class="vocab-card"><div class="vocab-word"><strong>${item.sv}</strong><span>Wort ${i+1}</span></div><div class="choice-grid">${getChoices(item,module,i).map((choice)=>`<label class="choice-option"><input type="radio" name="vocab-${i}" value="${choice}"><span>${choice}</span></label>`).join("")}</div></div>`).join("")+"<div class='actions'><button type='submit'>Voci prüfen</button></div>"}
function renderFlowButton(){const btn=byId("nextBtn");if(lastCheckedPassed===null){btn.classList.add("hidden");btn.hidden=true;return}btn.classList.remove("hidden");btn.hidden=false;btn.textContent=lastCheckedPassed?"WEITER":"NEUER VERSUCH"}
function renderFeedbackAction(passed){return `<div class="feedback-actions"><button class="feedback-flow-button ${passed?"success":"retry"}" data-feedback-flow="true" type="button">${passed?"WEITER":"NEUER VERSUCH"}</button></div>`}
function bookAudioFor(module){return bookAudio[sectionKey(module.id)]||[]}
function bookAudioPanel(module){const items=bookAudioFor(module);if(!items.length)return "";return `<li class="book-audio-item"><details class="book-audio"><summary>Buch-Audio privat</summary><div class="book-audio-grid">${items.map((item)=>`<div class="book-track"><span>${item.label}</span><audio controls preload="none" src="${item.src}"></audio></div>`).join("")}</div></details></li>`}
function audioRows(lines){return `<div class="audio-list">${lines.map((line)=>`<div class="audio-row"><span>${line}</span><div class="speak-actions"><button class="speak-button" data-speak="${encodeURIComponent(line)}" type="button">▶</button><button class="speak-button slow" data-speak="${encodeURIComponent(line)}" data-speed="slow" type="button">½</button></div></div>`).join("")}</div>`}
function drillBlock(title,lines){const clean=[...new Set(lines.filter(Boolean))].slice(0,6);if(!clean.length)return "";return `<div class="feedback-item warn"><strong>${title}</strong><ol>${clean.map((line)=>`<li><em>${line}</em><br>Schreibe diesen Ausdruck 3x laut und sauber ab. Danach erst neu versuchen.${audioRows([line])}</li>`).join("")}</ol></div>`}
function restartNotice(){return `<div class="feedback-item bad"><strong>Runde nicht bestanden.</strong>Der Bereich startet danach neu mit frischen Fragen. Kein halbes Durchmogeln, heute wird sauber gelernt.</div>`}
function checkVocab(module){const items=getVocabRound(module);const mistakes=[];items.forEach((item,i)=>{const selected=byId("vocabForm").querySelector(`input[name="vocab-${i}"]:checked`);if(!selected||selected.value!==item.de)mistakes.push({...item,selected:selected?.value||"keine Antwort"})});return {passed:mistakes.length===0,mistakes,items}}
function textSentences(text){return text.split(/\n|[.!?]+/).map((line)=>line.trim()).filter(Boolean)}
function hasExpected(input,expected){const exp=normalize(expected);if(!exp)return true;if(exp.includes(" "))return input.includes(exp);return input.split(" ").includes(exp)}
function analyzeCoachIssues(text,expected=[]){const issues=[];const raw=text;const input=normalize(text);coachRules.forEach((rule)=>{if(rule.pattern.test(raw)||rule.pattern.test(input))issues.push({key:rule.key,fix:rule.fix,explain:rule.explain})});pluralPairs.forEach(([singular,plural])=>{const singularHit=new RegExp(`\\b(två|tre|fyra|fem|sex|sju|åtta|nio|tio|elva|tolv|tretton|fjorton|femton|tjugo|trettio|hundra)\\s+${singular}\\b`,"i").test(input);if(singular!==plural&&singularHit)issues.push({key:`plural-${plural}`,fix:plural,explain:`Nach Zahlen ab 2 brauchst du hier den Plural: ${singular} -> ${plural}.`})});if(input.includes("det har"))issues.push({key:"har-det-finns",fix:"det finns",explain:"det har ist hier deutsch gedacht. Für 'es gibt' nutzt du det finns."});if(expected.some((x)=>normalize(x).startsWith("finns det"))&&input.includes("det finns"))issues.push({key:"question-order",fix:"Finns det ...?",explain:"Bei Ja/Nein-Fragen steht das Verb zuerst: Finns det ...?"});return uniqueIssues(issues)}
function uniqueIssues(issues){const seen=new Set();return issues.filter((issue)=>{if(seen.has(issue.key))return false;seen.add(issue.key);return true})}
function reviewCriteria(text){const input=normalize(text);const lines=textSentences(text);return [
  {label:"mindestens 5 kurze Sätze",ok:lines.length>=5},
  {label:"Name oder Wohnort genannt",ok:/\b(heter|bor|kommer)\b/.test(input)},
  {label:"mindestens eine Verneinung mit inte",ok:input.split(" ").includes("inte")},
  {label:"mindestens einmal kan oder vill",ok:input.split(" ").some((w)=>w==="kan"||w==="vill")},
  {label:"ein A1-Thema wie Familie, Arbeit, Wohnen, Essen oder Reise",ok:/\b(familj|mamma|pappa|syster|bror|arbete|jobbar|arbetar|lägenhet|rum|kaffe|frukost|resa|biljett)\b/.test(input)}
]}
function checkAnswer(text,ex,module){const input=normalize(text);const issues=analyzeCoachIssues(text,ex.expected);if(module.id==="a1review"){const criteria=reviewCriteria(text);const passed=criteria.every((item)=>item.ok)&&issues.length===0;const missing=criteria.filter((item)=>!item.ok).map((item)=>item.label);return {passed,hits:criteria.filter((item)=>item.ok).map((item)=>item.label),missing,criteria,issues}}const hits=ex.expected.filter((x)=>hasExpected(input,x));const missing=ex.expected.filter((x)=>!hasExpected(input,x));const passed=missing.length===0&&issues.length===0;return {passed,hits,missing,criteria:[],issues}}
function applyVocab(result,module){const s=getModuleState(module);state.today+=1;s.attempts+=1;if(result.passed){s.vocabStreak=1;if(s.status==="unsicher")s.status="Voci bestanden";s.exerciseSeed=nextSeed()}else{s.vocabStreak=0;s.vocabVariant+=1;s.vocabSeed=nextSeed();state.totalErrors+=Math.max(1,result.mistakes.length);state.errors.Voci=(state.errors.Voci||0)+result.mistakes.length}saveState()}
function updatePatternMemory(result,module){state.patterns=state.patterns||{};(result.issues||[]).forEach((issue)=>{const item=state.patterns[issue.key]||{status:"new",correct:0,errors:0,last:null};item.errors+=1;item.status=item.errors>=2?"shaky":"practicing";item.last=Date.now();state.patterns[issue.key]=item;state.errors[issue.key]=(state.errors[issue.key]||0)+1});if(result.passed){const key=`module-${module.id}`;const item=state.patterns[key]||{status:"new",correct:0,errors:0,last:null};item.correct+=1;item.status=item.correct>=3?"mastered":item.correct>=2?"stable":"practicing";item.last=Date.now();state.patterns[key]=item}}
function applyAnswer(result,module){const s=getModuleState(module);state.today+=1;s.attempts+=1;updatePatternMemory(result,module);if(result.passed){s.correctStreak=1;s.status="verstanden"}else{s.exerciseSeed=nextSeed();state.totalErrors+=1;state.errors.Satzbau=(state.errors.Satzbau||0)+1;s.status="unsicher"}saveState();return result.passed&&s.status==="verstanden"}
function showVocabFeedback(result){const fb=byId("feedback");if(result.passed){fb.innerHTML=`<h3>Voci-Korrektur</h3><div class="feedback-item ok"><strong>Voci sitzt.</strong>Alle 10 Wörter korrekt. Die Satzübung ist frei.</div><div class="feedback-item ok"><strong>Audio freigeschaltet</strong>${audioRows(result.items.map((x)=>x.sv))}</div>${renderFeedbackAction(true)}`}else{fb.innerHTML=`<h3>Voci-Korrektur</h3>${restartNotice()}<div class="feedback-item warn"><strong>Voci verkackt.</strong>Hier sind die genauen Treffer ins Knie. Erst drillen, dann neu starten.</div>${result.mistakes.map((x)=>`<div class="feedback-item bad"><strong>${x.sv}</strong>Deine Wahl: ${x.selected}<br>Korrekt: <em>${x.de}</em></div>`).join("")}${drillBlock("Kurz-Drill vor dem Neustart",result.mistakes.flatMap((x)=>[`${x.sv} = ${x.de}`,x.sv]))}${renderFeedbackAction(false)}`}fb.classList.remove("hidden")}
function issueBlock(issues){if(!issues?.length)return "";return `<div class="feedback-item warn"><strong>Coach-Korrektur</strong>${issues.map((issue)=>`<br><em>${issue.fix}</em>: ${issue.explain}`).join("")}</div>`}
function coachRepeatLines(result,ex){const lines=[...(result.missing||[])];(result.issues||[]).slice(0,2).forEach((issue)=>{if(issue.key==="talar-tala")lines.push("Jag talar svenska.","Jag kan tala svenska.");else if(issue.key==="bor-bo")lines.push("Jag bor i Schweiz.","Jag vill bo i Sverige.");else if(issue.key==="inte-position")lines.push("Jag talar inte svenska.","Jag kan inte tala svenska.");else if(issue.key==="har-det-finns")lines.push("Det finns tre biljetter.","Jag har en biljett.");else lines.push(issue.fix)});return unique(lines).slice(0,3)}
function showAnswerFeedback(result,module,ex){const s=getModuleState(module);const fb=byId("feedback");const msg=result.passed?winMessages[Math.floor(Math.random()*winMessages.length)]:roastMessages[Math.floor(Math.random()*roastMessages.length)];let html=`<h3>Korrektur</h3><div class="feedback-item ${result.passed?"ok":"warn"}"><strong>${msg}</strong>${result.passed?"Kurzer Durchgang bestanden.":"Diese Runde zählt als nicht bestanden."}</div>`;if(result.criteria?.length)html+=`<div class="feedback-item ${result.passed?"ok":"warn"}"><strong>A1-Kriterien</strong>${result.criteria.map((item)=>`<br>${item.ok?"✓":"✗"} ${item.label}`).join("")}</div>`;html+=issueBlock(result.issues);if(!result.passed)html+=restartNotice();if(result.missing.length)html+=`<div class="feedback-item bad"><strong>Fehlt oder zu anders formuliert</strong>${result.missing.map((x)=>`<br><em>${x}</em>`).join("")}</div>`;const repeat=coachRepeatLines(result,ex);if(!result.passed&&repeat.length)html+=drillBlock("Jetzt nur diese Mini-Wiederholung",repeat);if(result.passed)html+=`<div class="feedback-item ok"><strong>Aussprache freigeschaltet</strong>${audioRows(ex.expected)}</div>`;if(s.status==="verstanden")html+=`<div class="feedback-item ok"><strong>Nächstes Thema bereit</strong>Mit WEITER geht es zur nächsten Kategorie.</div>`;fb.innerHTML=html+renderFeedbackAction(result.passed);fb.classList.remove("hidden")}
function goNext(){const module=activeModule();const s=getModuleState(module);if(lastCheckedMode==="vocab"){if(!lastCheckedPassed){s.vocabVariant+=1;s.vocabSeed=nextSeed()}else{s.exerciseSeed=nextSeed()}}else if(!lastCheckedPassed){s.variant+=1;s.exerciseSeed=nextSeed()}else if(s.correctStreak>=1){const next=moduleIndex(module.id)+1;if(next<modules.length){state.activeModule=modules[next].id;const nextState=getModuleState(modules[next]);nextState.vocabSeed=nextSeed();nextState.exerciseSeed=nextSeed()}}lastCheckedPassed=null;lastCheckedMode=null;byId("answerInput").value="";byId("feedback").classList.add("hidden");saveState();render()}
function refreshVoices(){voices=(speechSynthesis?.getVoices?.()||[]).filter((v)=>/^sv/i.test(v.lang)||/swedish|svenska|bengt/i.test(v.name))}
function voice(){return voices[0]||null}
function speakSwedish(text,speed="normal"){if(!("speechSynthesis" in window)){alert("Dein Browser unterstützt keine Sprachausgabe.");return}refreshVoices();const v=voice();if(!v){alert("Keine schwedische Stimme gefunden. Installiere in Windows eine schwedische Sprache/Stimme oder nutze Edge/Chrome mit einer sv-SE Stimme.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="sv-SE";u.voice=v;u.rate=speed==="slow"?.72:.9;u.pitch=1;speechSynthesis.speak(u)}
function celebration(){const c=byId("celebration");c.classList.remove("fly");void c.offsetWidth;c.classList.add("fly");try{const ctx=new (window.AudioContext||window.webkitAudioContext)();[880,1175,1568].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;g.gain.value=.02;o.connect(g);g.connect(ctx.destination);o.start(ctx.currentTime+i*.08);o.stop(ctx.currentTime+i*.08+.25)})}catch{}}
async function copyChar(char,button){try{await navigator.clipboard.writeText(char);button.dataset.tooltip="copied";button.classList.add("copied");setTimeout(()=>{button.dataset.tooltip="copy";button.classList.remove("copied")},900)}catch{byId("answerInput").focus();document.execCommand("insertText",false,char)}}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem("svenska-a1-theme",theme);const btn=byId("themeBtn");if(btn)btn.textContent=theme==="dark"?"Hell":"Dunkel"}
function initTheme(){const saved=localStorage.getItem("svenska-a1-theme");const preferred=window.matchMedia?.("(prefers-color-scheme: dark)")?.matches?"dark":"light";applyTheme(saved||preferred)}
byId("moduleList").addEventListener("click",(e)=>{const b=e.target.closest("[data-module]");if(!b||b.disabled)return;state.activeModule=b.dataset.module;lastCheckedPassed=null;lastCheckedMode=null;byId("feedback").classList.add("hidden");saveState();render()});
byId("vocabForm").addEventListener("submit",(e)=>{e.preventDefault();const m=activeModule();const r=checkVocab(m);applyVocab(r,m);lastCheckedPassed=r.passed;lastCheckedMode="vocab";render();showVocabFeedback(r);renderFlowButton()});
byId("answerForm").addEventListener("submit",(e)=>{e.preventDefault();const text=byId("answerInput").value.trim();if(!text)return;const m=activeModule();const ex=exercise(m);const r=checkAnswer(text,ex,m);const mastered=applyAnswer(r,m);lastCheckedPassed=r.passed;lastCheckedMode="exercise";render();showAnswerFeedback(r,m,ex);renderFlowButton();if(mastered)celebration()});
byId("nextBtn").addEventListener("click",goNext);byId("feedback").addEventListener("click",(e)=>{const flow=e.target.closest("[data-feedback-flow]");if(flow)return goNext();const speak=e.target.closest("[data-speak]");if(speak)speakSwedish(decodeURIComponent(speak.dataset.speak),speak.dataset.speed||"normal")});
document.querySelectorAll("[data-copy-char]").forEach((b)=>{b.addEventListener("click",()=>copyChar(b.dataset.copyChar,b));b.addEventListener("mouseenter",()=>copyChar(b.dataset.copyChar,b))});
byId("themeBtn")?.addEventListener("click",()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark"));
byId("resetBtn").addEventListener("click",()=>{if(!confirm("Fortschritt wirklich zurücksetzen?"))return;localStorage.removeItem("svenska-a1-state");state=loadState();lastCheckedPassed=null;lastCheckedMode=null;byId("answerInput").value="";byId("feedback").classList.add("hidden");render()});
initTheme();resetLegacy();refreshVoices();if("speechSynthesis" in window)speechSynthesis.onvoiceschanged=refreshVoices;render();
